#IMPORTING LIBRARIES

In [1]:
import pandas as pd
import sys
print(sys.version)
print('pandas version', pd.__version__)

3.12.0 (v3.12.0:0fb18b02c8, Oct  2 2023, 09:45:56) [Clang 13.0.0 (clang-1300.0.29.30)]
pandas version 2.1.3

I/O(Reading and Writing)

In [6]:
%pip install pyarrow

Collecting pyarrow
  Downloading pyarrow-19.0.0-cp312-cp312-macosx_12_0_arm64.whl.metadata (3.3 kB)
Downloading pyarrow-19.0.0-cp312-cp312-macosx_12_0_arm64.whl (30.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 30.7/30.7 MB 7.8 MB/s eta 0:00:0000:0100:01m
Installing collected packages: pyarrow
Successfully installed pyarrow-19.0.0
Note: you may need to restart the kernel to use updated packages.

In [7]:
%pip install fastparquet

Collecting fastparquet
  Downloading fastparquet-2024.11.0-cp312-cp312-macosx_11_0_arm64.whl.metadata (4.2 kB)
Requirement already satisfied: pandas>=1.5.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from fastparquet) (2.1.3)
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from fastparquet) (1.26.2)
Collecting cramjam>=2.3 (from fastparquet)
  Downloading cramjam-2.9.1-cp312-cp312-macosx_11_0_arm64.whl.metadata (4.9 kB)
Collecting fsspec (from fastparquet)
  Downloading fsspec-2025.2.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: packaging in ./Library/Python/3.12/lib/python/site-packages (from fastparquet) (23.2)
Requirement already satisfied: python-dateutil>=2.8.2 in ./Library/Python/3.12/lib/python/site-packages (from pandas>=1.5.0->fastparquet) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas>=1.5.0->fastparquet) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas>=1.5.0->fastparquet) (2023.3)
Requirement already satisfied: six>=1.5 in ./Library/Python/3.12/lib/python/site-packages (from python-dateutil>=2.8.2->pandas>=1.5.0->fastparquet) (1.16.0)
Downloading fastparquet-2024.11.0-cp312-cp312-macosx_11_0_arm64.whl (685 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 685.4/685.4 kB 4.5 MB/s eta 0:00:00a 0:00:01
Downloading cramjam-2.9.1-cp312-cp312-macosx_11_0_arm64.whl (1.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 17.4 MB/s eta 0:00:00
Downloading fsspec-2025.2.0-py3-none-any.whl (184 kB)
Installing collected packages: fsspec, cramjam, fastparquet
Successfully installed cramjam-2.9.1 fastparquet-2024.11.0 fsspec-2025.2.0
Note: you may need to restart the kernel to use updated packages.

In [8]:
df=pd.read_parquet('Combined_Flights_2018.parquet')

In [9]:
type(df)

pandas.core.frame.DataFrame

In [10]:
df.to_csv('Combined_Flights_2018.csv', index=False)

Dataframe Basics

In [12]:
#to unhide the middle columns 
pd.set_option('display.max_columns', 500)

In [14]:
df.head(10)

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
0,2018-01-23,Endeavor Air Inc.,ABY,ATL,False,False,1202,1157.0,0.0,-5.0,1256.0,0.0,38.0,62.0,59.0,145.0,2018,1,1,23,2,DL,DL_CODESHARE,19790,DL,3298,9E,20363,9E,N8928A,3298,10146,1014602,30146,"Albany, GA",GA,13,Georgia,34,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,0.0,-1.0,1200-1259,14.0,1211.0,1249.0,7.0,1304,-8.0,0.0,-1.0,1300-1359,1,0.0
1,2018-01-24,Endeavor Air Inc.,ABY,ATL,False,False,1202,1157.0,0.0,-5.0,1258.0,0.0,36.0,62.0,61.0,145.0,2018,1,1,24,3,DL,DL_CODESHARE,19790,DL,3298,9E,20363,9E,N800AY,3298,10146,1014602,30146,"Albany, GA",GA,13,Georgia,34,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,0.0,-1.0,1200-1259,13.0,1210.0,1246.0,12.0,1304,-6.0,0.0,-1.0,1300-1359,1,0.0
2,2018-01-25,Endeavor Air Inc.,ABY,ATL,False,False,1202,1153.0,0.0,-9.0,1302.0,0.0,40.0,62.0,69.0,145.0,2018,1,1,25,4,DL,DL_CODESHARE,19790,DL,3298,9E,20363,9E,N8836A,3298,10146,1014602,30146,"Albany, GA",GA,13,Georgia,34,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,0.0,-1.0,1200-1259,18.0,1211.0,1251.0,11.0,1304,-2.0,0.0,-1.0,1300-1359,1,0.0
3,2018-01-26,Endeavor Air Inc.,ABY,ATL,False,False,1202,1150.0,0.0,-12.0,1253.0,0.0,35.0,62.0,63.0,145.0,2018,1,1,26,5,DL,DL_CODESHARE,19790,DL,3298,9E,20363,9E,N800AY,3298,10146,1014602,30146,"Albany, GA",GA,13,Georgia,34,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,0.0,-1.0,1200-1259,17.0,1207.0,1242.0,11.0,1304,-11.0,0.0,-1.0,1300-1359,1,0.0
4,2018-01-27,Endeavor Air Inc.,ABY,ATL,False,False,1400,1355.0,0.0,-5.0,1459.0,0.0,36.0,60.0,64.0,145.0,2018,1,1,27,6,DL,DL_CODESHARE,19790,DL,3298,9E,20363,9E,N8839E,3298,10146,1014602,30146,"Albany, GA",GA,13,Georgia,34,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,0.0,-1.0,1400-1459,17.0,1412.0,1448.0,11.0,1500,-1.0,0.0,-1.0,1500-1559,1,0.0
5,2018-01-28,Endeavor Air Inc.,ABY,ATL,False,False,1202,1202.0,NaN,NaN,1326.0,22.0,37.0,62.0,84.0,145.0,2018,1,1,28,7,DL,DL_CODESHARE,19790,DL,3298,9E,20363,9E,N8918B,3298,10146,1014602,30146,"Albany, GA",GA,13,Georgia,34,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,NaN,NaN,1200-1259,34.0,1236.0,1313.0,13.0,1304,22.0,1.0,1.0,1300-1359,1,0.0
6,2018-01-29,Endeavor Air Inc.,ABY,ATL,False,False,1202,1204.0,2.0,2.0,1303.0,0.0,34.0,62.0,59.0,145.0,2018,1,1,29,1,DL,DL_CODESHARE,19790,DL,3298,9E,20363,9E,N8783E,3298,10146,1014602,30146,"Albany, GA",GA,13,Georgia,34,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,0.0,0.0,1200-1259,15.0,1219.0,1253.0,10.0,1304,-1.0,0.0,-1.0,1300-1359,1,0.0
7,2018-01-30,Endeavor Air Inc.,ABY,ATL,False,False,1202,1153.0,0.0,-9.0,1255.0,0.0,44.0,62.0,62.0,145.0,2018,1,1,30,2,DL,DL_CODESHARE,19790,DL,3298,9E,20363,9E,N8946A,3298,10146,1014602,30146,"Albany, GA",GA,13,Georgia,34,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,0.0,-1.0,1200-1259,7.0,1200.0,1244.0,11.0,1304,-9.0,0.0,-1.0,1300-1359,1,0.0
8,2018-01-31,Endeavor Air Inc.,ABY,ATL,False,False,1202,1153.0,0.0,-9.0,1304.0,NaN,37.0,62.0,71.0,145.0,2018,1,1,31,3,DL,DL_CODESHARE,19790,DL,3298,9E,20363,9E,N8918B,3298,10146,1014602,30146,"Albany, GA",GA,13,Georgia,34,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,0.0,-1.0,1200-1259,26.0,1219.0,1256.0,8.0,1304,NaN,NaN,NaN,1300-1359,1,0.0
9,2018-01-03,Endeavor Air Inc.,ATL,ABY,False,False,1037,1101.0,24.0,24.0,1159.0,22.0,32.0,60.0,58.0,145.0,2018,1,1,3,3,DL,DL_CODESHARE,19790,DL,3298,9E,20363,9E,N981EV,3298,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,10146,1014602,30146,"Albany, GA",GA,13,Georgia,34,1.0,1.0,1000-1059,23.0,1124.0,1156.0,3.0,1137,22.0,1.0,1.0,1100-1159,1,0.0

In [15]:
df.tail()

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
637609,2018-09-11,Air Wisconsin Airlines Corp,SCE,IAD,False,False,1445,1433.0,0.0,-12.0,1515.0,0.0,35.0,61.0,42.0,133.0,2018,3,9,11,2,UA,UA_CODESHARE,19977,UA,3839,ZW,20046,ZW,N437AW,3839,14711,1471105,34711,"State College, PA",PA,42,Pennsylvania,23,12264,1226402,30852,"Washington, DC",VA,51,Virginia,38,0.0,-1.0,1400-1459,4.0,1437.0,1512.0,3.0,1546,-31.0,0.0,-2.0,1500-1559,1,0.0
637610,2018-09-11,Air Wisconsin Airlines Corp,IAD,GSO,False,False,1235,1224.0,0.0,-11.0,1344.0,0.0,43.0,80.0,80.0,239.0,2018,3,9,11,2,UA,UA_CODESHARE,19977,UA,3838,ZW,20046,ZW,N410AW,3838,12264,1226402,30852,"Washington, DC",VA,51,Virginia,38,11995,1199502,31995,"Greensboro/High Point, NC",NC,37,North Carolina,36,0.0,-1.0,1200-1259,30.0,1254.0,1337.0,7.0,1355,-11.0,0.0,-1.0,1300-1359,1,0.0
637611,2018-09-11,Air Wisconsin Airlines Corp,EVV,ORD,False,False,1030,1016.0,0.0,-14.0,1137.0,0.0,54.0,94.0,81.0,272.0,2018,3,9,11,2,UA,UA_CODESHARE,19977,UA,3837,ZW,20046,ZW,N467AW,3837,11612,1161206,31612,"Evansville, IN",IN,18,Indiana,42,13930,1393006,30977,"Chicago, IL",IL,17,Illinois,41,0.0,-1.0,1000-1059,20.0,1036.0,1130.0,7.0,1204,-27.0,0.0,-2.0,1200-1259,2,0.0
637612,2018-09-11,Air Wisconsin Airlines Corp,ORD,HPN,False,False,1410,1403.0,0.0,-7.0,1717.0,0.0,104.0,136.0,134.0,738.0,2018,3,9,11,2,UA,UA_CODESHARE,19977,UA,3837,ZW,20046,ZW,N440AW,3837,13930,1393006,30977,"Chicago, IL",IL,17,Illinois,41,12197,1219702,31703,"White Plains, NY",NY,36,New York,22,0.0,-1.0,1400-1459,25.0,1428.0,1712.0,5.0,1726,-9.0,0.0,-1.0,1700-1759,3,0.0
637613,2018-09-11,Air Wisconsin Airlines Corp,HPN,ORD,False,False,1800,1754.0,0.0,-6.0,1919.0,0.0,116.0,153.0,145.0,738.0,2018,3,9,11,2,UA,UA_CODESHARE,19977,UA,3836,ZW,20046,ZW,N440AW,3836,12197,1219702,31703,"White Plains, NY",NY,36,New York,22,13930,1393006,30977,"Chicago, IL",IL,17,Illinois,41,0.0,-1.0,1800-1859,14.0,1808.0,1904.0,15.0,1933,-14.0,0.0,-1.0,1900-1959,3,0.0

In [17]:
#random subset of the dataset
df.sample(5)

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
363270,2018-09-27,SkyWest Airlines Inc.,SAN,SMF,False,False,1725,1714.0,0.0,-11.0,1901.0,0.0,82.0,103.0,107.0,480.0,2018,3,9,27,4,AS,AS_CODESHARE,19930,AS,3344,OO,20304,OO,N182SY,3344,14679,1467903,33570,"San Diego, CA",CA,6,California,91,14893,1489302,33192,"Sacramento, CA",CA,6,California,91,0.0,-1.0,1700-1759,19.0,1733.0,1855.0,6.0,1908,-7.0,0.0,-1.0,1900-1959,2,0.0
454418,2018-09-28,Hawaiian Airlines Inc.,LAX,OGG,False,False,900,854.0,0.0,-6.0,1144.0,4.0,325.0,340.0,350.0,2486.0,2018,3,9,28,5,HA,HA,19690,HA,33,HA,19690,HA,N395HA,33,12892,1289208,32575,"Los Angeles, CA",CA,6,California,91,13830,1383002,33830,"Kahului, HI",HI,15,Hawaii,2,0.0,-1.0,0900-0959,19.0,913.0,1138.0,6.0,1140,4.0,0.0,0.0,1100-1159,10,0.0
165268,2018-05-07,Southwest Airlines Co.,BOS,STL,False,False,1830,1825.0,0.0,-5.0,2011.0,0.0,140.0,190.0,166.0,1047.0,2018,2,5,7,1,WN,WN,19393,WN,610,WN,19393,WN,N253WN,610,10721,1072102,30721,"Boston, MA",MA,25,Massachusetts,13,15016,1501606,31123,"St. Louis, MO",MO,29,Missouri,64,0.0,-1.0,1800-1859,21.0,1846.0,2006.0,5.0,2040,-29.0,0.0,-2.0,2000-2059,5,0.0
223204,2018-09-26,Southwest Airlines Co.,HOU,DAL,False,False,1600,1801.0,121.0,121.0,1853.0,108.0,40.0,65.0,52.0,239.0,2018,3,9,26,3,WN,WN,19393,WN,40,WN,19393,WN,N458WN,40,12191,1219102,31453,"Houston, TX",TX,48,Texas,74,11259,1125903,30194,"Dallas, TX",TX,48,Texas,74,1.0,8.0,1600-1659,8.0,1809.0,1849.0,4.0,1705,108.0,1.0,7.0,1700-1759,1,0.0
296050,2018-07-25,United Air Lines Inc.,DEN,SNA,False,False,1115,1111.0,0.0,-4.0,1222.0,0.0,112.0,136.0,131.0,846.0,2018,3,7,25,3,UA,UA,19977,UA,403,UA,19977,UA,N12218,403,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,14908,1490803,32575,"Santa Ana, CA",CA,6,California,91,0.0,-1.0,1100-1159,13.0,1124.0,1216.0,6.0,1231,-9.0,0.0,-1.0,1200-1259,4,0.0

In [18]:
df.sample(frac=0.1)

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
11903,2018-01-12,ExpressJet Airlines Inc.,EWR,BWI,False,False,1045,1041.0,0.0,-4.0,1152.0,0.0,41.0,89.0,71.0,169.0,2018,1,1,12,5,UA,UA_CODESHARE,19977,UA,4121,EV,20366,EV,N14902,4121,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,10821,1082106,30852,"Baltimore, MD",MD,24,Maryland,35,0.0,-1.0,1000-1059,23.0,1104.0,1145.0,7.0,1214,-22.0,0.0,-2.0,1200-1259,1,0.0
191061,2018-06-03,Spirit Air Lines,MCO,ATL,False,False,620,616.0,0.0,-4.0,741.0,0.0,62.0,92.0,85.0,404.0,2018,2,6,3,7,NK,NK,20416,NK,768,NK,20416,NK,N615NK,768,13204,1320402,31454,"Orlando, FL",FL,12,Florida,33,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,0.0,-1.0,0600-0659,17.0,633.0,735.0,6.0,752,-11.0,0.0,-1.0,0700-0759,2,0.0
140377,2018-11-19,Delta Air Lines Inc.,ATL,LAX,False,False,1230,1230.0,0.0,0.0,1425.0,0.0,266.0,297.0,295.0,1947.0,2018,4,11,19,1,DL,DL,19790,DL,1139,DL,19790,DL,N539US,1139,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,12892,1289208,32575,"Los Angeles, CA",CA,6,California,91,0.0,0.0,1200-1259,20.0,1250.0,1416.0,9.0,1427,-2.0,0.0,-1.0,1400-1459,8,0.0
85825,2018-09-04,Alaska Airlines Inc.,EWR,SEA,False,False,600,553.0,0.0,-7.0,842.0,0.0,320.0,361.0,349.0,2402.0,2018,3,9,4,2,AS,AS,19930,AS,31,AS,19930,AS,N464AS,31,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,14747,1474703,30559,"Seattle, WA",WA,53,Washington,93,0.0,-1.0,0600-0659,21.0,614.0,834.0,8.0,901,-19.0,0.0,-2.0,0900-0959,10,0.0
428990,2018-12-10,United Air Lines Inc.,LGA,IAH,False,False,1549,1553.0,4.0,4.0,1849.0,0.0,190.0,242.0,236.0,1416.0,2018,4,12,10,1,UA,UA,19977,UA,833,UA,19977,UA,N835UA,833,12953,1295304,31703,"New York, NY",NY,36,New York,22,12266,1226603,31453,"Houston, TX",TX,48,Texas,74,0.0,0.0,1500-1559,42.0,1635.0,1845.0,4.0,1851,-2.0,0.0,-1.0,1800-1859,6,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129658,2018-10-25,JetBlue Airways,DEN,JFK,False,False,1235,1340.0,65.0,65.0,1922.0,63.0,195.0,224.0,222.0,1626.0,2018,4,10,25,4,B6,B6,20409,B6,576,B6,20409,B6,N975JB,576,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,12478,1247805,31703,"New York, NY",NY,36,New York,22,1.0,4.0,1200-1259,18.0,1358.0,1913.0,9.0,1819,63.0,1.0,4.0,1800-1859,7,0.0
452706,2018-09-14,Delta Air Lines Inc.,SFO,LAX,False,False,1915,1913.0,0.0,-2.0,2048.0,0.0,59.0,110.0,95.0,337.0,2018,3,9,14,5,DL,DL,19790,DL,2670,DL,19790,DL,N958AT,2670,14771,1477104,32457,"San Francisco, CA",CA,6,California,91,12892,1289208,32575,"Los Angeles, CA",CA,6,California,91,0.0,-1.0,1900-1959,28.0,1941.0,2040.0,8.0,2105,-17.0,0.0,-2.0,2100-2159,2,0.0
384904,2018-09-23,Southwest Airlines Co.,SLC,PHX,False,False,720,731.0,11.0,11.0,757.0,2.0,72.0,95.0,86.0,507.0,2018,3,9,23,7,WN,WN,19393,WN,6617,WN,19393,WN,N7732A,6617,14869,1486903,34614,"Salt Lake City, UT",UT,49,Utah,87,14107,1410702,30466,"Phoenix, AZ",AZ,4,Arizona,81,0.0,0.0,0700-0759,10.0,741.0,753.0,4.0,755,2.0,0.0,0.0,0700-0759,3,0.0
463093,2018-10-20,Delta Air Lines Inc.,JAN,ATL,False,False,715,912.0,117.0,117.0,1124.0,112.0,51.0,77.0,72.0,341.0,2018,4,10,20,6,DL,DL,19790,DL,2990,DL,19790,DL,N978DL,2990,12448,1244807,32448,"Jackson/Vicksburg, MS",MS,28,Mississippi,53,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,1.0,7.0,0700-0759,12.0,924.0,1115.0,9.0,932,112.0,1.0,7.0,0900-0959,2,0.0
288914,2018-11-19,Comair Inc.,CRW,DCA,False,False,1952,1952.0,0.0,0.0,2048.0,0.0,41.0,69.0,56.0,249.0,2018,4,11,19,1,AA,AA_CODESHARE,19805,AA,5666,OH,20397,OH,N250PS,5666,11146,1114606,31146,"Charleston/Dunbar, WV",WV,54,West Virginia,39,11278,1127805,30852,"Washington, DC",VA,51,Virginia,38,0.0,0.0,1900-1959,7.0,1959.0,2040.0,8.0,2101,-13.0,0.0,-1.0,2100-2159,1,0.0

In [19]:
# adding random_state helps with reproducability
df.sample(frac=0.1, random_state=529)

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
148734,2018-03-18,Republic Airlines,ORD,IND,False,False,1950,1945.0,0.0,-5.0,2153.0,0.0,31.0,66.0,68.0,177.0,2018,1,3,18,7,UA,UA_CODESHARE,19977,UA,3480,YX,20452,YX,N740YX,3480,13930,1393006,30977,"Chicago, IL",IL,17,Illinois,41,12339,1233904,32337,"Indianapolis, IN",IN,18,Indiana,42,0.0,-1.0,1900-1959,31.0,2016.0,2147.0,6.0,2156,-3.0,0.0,-1.0,2100-2159,1,0.0
388794,2018-08-08,Envoy Air,DSM,ORD,False,False,1947,1937.0,0.0,-10.0,2054.0,0.0,53.0,88.0,77.0,299.0,2018,3,8,8,3,AA,AA_CODESHARE,19805,AA,3455,MQ,20398,MQ,N239NN,3455,11423,1142306,31423,"Des Moines, IA",IA,19,Iowa,61,13930,1393006,30977,"Chicago, IL",IL,17,Illinois,41,0.0,-1.0,1900-1959,8.0,1945.0,2038.0,16.0,2115,-21.0,0.0,-2.0,2100-2159,2,0.0
152965,2018-12-03,SkyWest Airlines Inc.,LGA,ORD,False,False,715,748.0,33.0,33.0,930.0,30.0,127.0,165.0,162.0,733.0,2018,4,12,3,1,DL,DL_CODESHARE,19790,DL,3599,OO,20304,OO,N268SY,3599,12953,1295304,31703,"New York, NY",NY,36,New York,22,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,1.0,2.0,0700-0759,23.0,811.0,918.0,12.0,900,30.0,1.0,2.0,0900-0959,3,0.0
100336,2018-02-09,Southwest Airlines Co.,FLL,MDW,True,False,630,NaN,NaN,NaN,NaN,NaN,NaN,190.0,NaN,1167.0,2018,1,2,9,5,WN,WN,19393,WN,931,WN,19393,WN,N8322X,931,11697,1169706,32467,"Fort Lauderdale, FL",FL,12,Florida,33,13232,1323202,30977,"Chicago, IL",IL,17,Illinois,41,NaN,NaN,0600-0659,NaN,NaN,NaN,NaN,840,NaN,NaN,NaN,0800-0859,5,0.0
501981,2018-09-02,Comair Inc.,CLT,MHT,False,False,2209,2207.0,0.0,-2.0,2.0,0.0,104.0,123.0,115.0,737.0,2018,3,9,2,7,AA,AA_CODESHARE,19805,AA,5655,OH,20397,OH,N583NN,5655,11057,1105703,31057,"Charlotte, NC",NC,37,North Carolina,36,13296,1329604,30721,"Manchester, NH",NH,33,New Hampshire,14,0.0,-1.0,2200-2259,7.0,2214.0,2358.0,4.0,12,-10.0,0.0,-1.0,0001-0559,3,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
351208,2018-11-13,Southwest Airlines Co.,ABQ,LAS,False,False,2120,2113.0,0.0,-7.0,2132.0,0.0,68.0,95.0,79.0,486.0,2018,4,11,13,2,WN,WN,19393,WN,1528,WN,19393,WN,N463WN,1528,10140,1014005,30140,"Albuquerque, NM",NM,35,New Mexico,86,12889,1288903,32211,"Las Vegas, NV",NV,32,Nevada,85,0.0,-1.0,2100-2159,7.0,2120.0,2128.0,4.0,2155,-23.0,0.0,-2.0,2100-2159,2,0.0
595828,2018-09-10,Alaska Airlines Inc.,SEA,LAX,False,False,850,851.0,1.0,1.0,1129.0,0.0,126.0,166.0,158.0,954.0,2018,3,9,10,1,AS,AS,19930,AS,1154,AS,19930,AS,N840VA,1154,14747,1474703,30559,"Seattle, WA",WA,53,Washington,93,12892,1289208,32575,"Los Angeles, CA",CA,6,California,91,0.0,0.0,0800-0859,14.0,905.0,1111.0,18.0,1136,-7.0,0.0,-1.0,1100-1159,4,0.0
373533,2018-12-21,Delta Air Lines Inc.,ORD,ATL,False,False,1716,1735.0,19.0,19.0,2035.0,16.0,88.0,123.0,120.0,606.0,2018,4,12,21,5,DL,DL,19790,DL,343,DL,19790,DL,N916DE,343,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,1.0,1.0,1700-1759,27.0,1802.0,2030.0,5.0,2019,16.0,1.0,1.0,2000-2059,3,0.0
275009,2018-09-23,Alaska Airlines Inc.,TUS,SEA,False,False,1140,1137.0,0.0,-3.0,1446.0,0.0,168.0,187.0,189.0,1216.0,2018,3,9,23,7,AS,AS,19930,AS,641,AS,19930,AS,N448AS,641,15376,1537603,30436,"Tucson, AZ",AZ,4,Arizona,81,14747,1474703,30559,"Seattle, WA",WA,53,Washington,93,0.0,-1.0,1100-1159,10.0,1147.0,1435.0,11.0,1447,-1.0,0.0,-1.0,1400-1459,5,0.0
171802,2018-06-11,JetBlue Airways,BOS,CLE,False,False,2152,2143.0,0.0,-9.0,2325.0,0.0,83.0,125.0,102.0,563.0,2018,2,6,11,1,B6,B6,20409,B6,1841,B6,20409,B6,N266JB,1841,10721,1072102,30721,"Boston, MA",MA,25,Massachusetts,13,11042,1104205,30647,"Cleveland, OH",OH,39,Ohio,44,0.0,-1.0,2100-2159,14.0,2157.0,2320.0,5.0,2357,-32.0,0.0,-2.0,2300-2359,3,0.0

In [20]:
#Columns and Index
df.columns

Index(['FlightDate', 'Airline', 'Origin', 'Dest', 'Cancelled', 'Diverted',
       'CRSDepTime', 'DepTime', 'DepDelayMinutes', 'DepDelay', 'ArrTime',
       'ArrDelayMinutes', 'AirTime', 'CRSElapsedTime', 'ActualElapsedTime',
       'Distance', 'Year', 'Quarter', 'Month', 'DayofMonth', 'DayOfWeek',
       'Marketing_Airline_Network', 'Operated_or_Branded_Code_Share_Partners',
       'DOT_ID_Marketing_Airline', 'IATA_Code_Marketing_Airline',
       'Flight_Number_Marketing_Airline', 'Operating_Airline',
       'DOT_ID_Operating_Airline', 'IATA_Code_Operating_Airline',
       'Tail_Number', 'Flight_Number_Operating_Airline', 'OriginAirportID',
       'OriginAirportSeqID', 'OriginCityMarketID', 'OriginCityName',
       'OriginState', 'OriginStateFips', 'OriginStateName', 'OriginWac',
       'DestAirportID', 'DestAirportSeqID', 'DestCityMarketID', 'DestCityName',
       'DestState', 'DestStateFips', 'DestStateName', 'DestWac', 'DepDel15',
       'DepartureDelayGroups', 'DepTimeBlk', 'TaxiOut', 'WheelsOff',
       'WheelsOn', 'TaxiIn', 'CRSArrTime', 'ArrDelay', 'ArrDel15',
       'ArrivalDelayGroups', 'ArrTimeBlk', 'DistanceGroup',
       'DivAirportLandings'],
      dtype='object')

In [21]:
df.index

Index([     0,      1,      2,      3,      4,      5,      6,      7,      8,
            9,
       ...
       637604, 637605, 637606, 637607, 637608, 637609, 637610, 637611, 637612,
       637613],
      dtype='int64', length=5689512)

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5689512 entries, 0 to 637613
Data columns (total 61 columns):
 #   Column                                   Dtype
---  ------                                   -----
 0   FlightDate                               datetime64[us]
 1   Airline                                  object
 2   Origin                                   object
 3   Dest                                     object
 4   Cancelled                                bool
 5   Diverted                                 bool
 6   CRSDepTime                               int64
 7   DepTime                                  float64
 8   DepDelayMinutes                          float64
 9   DepDelay                                 float64
 10  ArrTime                                  float64
 11  ArrDelayMinutes                          float64
 12  AirTime                                  float64
 13  CRSElapsedTime                           float64
 14  ActualElapsedTime                        float64
 15  Distance                                 float64
 16  Year                                     int64
 17  Quarter                                  int64
 18  Month                                    int64
 19  DayofMonth                               int64
 20  DayOfWeek                                int64
 21  Marketing_Airline_Network                object
 22  Operated_or_Branded_Code_Share_Partners  object
 23  DOT_ID_Marketing_Airline                 int64
 24  IATA_Code_Marketing_Airline              object
 25  Flight_Number_Marketing_Airline          int64
 26  Operating_Airline                        object
 27  DOT_ID_Operating_Airline                 int64
 28  IATA_Code_Operating_Airline              object
 29  Tail_Number                              object
 30  Flight_Number_Operating_Airline          int64
 31  OriginAirportID                          int64
 32  OriginAirportSeqID                       int64
 33  OriginCityMarketID                       int64
 34  OriginCityName                           object
 35  OriginState                              object
 36  OriginStateFips                          int64
 37  OriginStateName                          object
 38  OriginWac                                int64
 39  DestAirportID                            int64
 40  DestAirportSeqID                         int64
 41  DestCityMarketID                         int64
 42  DestCityName                             object
 43  DestState                                object
 44  DestStateFips                            int64
 45  DestStateName                            object
 46  DestWac                                  int64
 47  DepDel15                                 float64
 48  DepartureDelayGroups                     float64
 49  DepTimeBlk                               object
 50  TaxiOut                                  float64
 51  WheelsOff                                float64
 52  WheelsOn                                 float64
 53  TaxiIn                                   float64
 54  CRSArrTime                               int64
 55  ArrDelay                                 float64
 56  ArrDel15                                 float64
 57  ArrivalDelayGroups                       float64
 58  ArrTimeBlk                               object
 59  DistanceGroup                            int64
 60  DivAirportLandings                       float64
dtypes: bool(2), datetime64[us](1), float64(19), int64(22), object(17)
memory usage: 2.6+ GB

In [24]:
df.info(verbose=False)

<class 'pandas.core.frame.DataFrame'>
Index: 5689512 entries, 0 to 637613
Columns: 61 entries, FlightDate to DivAirportLandings
dtypes: bool(2), datetime64[us](1), float64(19), int64(22), object(17)
memory usage: 2.6+ GB

In [25]:
df.describe()

,FlightDate,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,DOT_ID_Marketing_Airline,Flight_Number_Marketing_Airline,DOT_ID_Operating_Airline,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginStateFips,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestStateFips,DestWac,DepDel15,DepartureDelayGroups,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,DistanceGroup,DivAirportLandings
count,5689512,5.689512e+06,5.604132e+06,5.602937e+06,5.602937e+06,5.598897e+06,5.586619e+06,5.580241e+06,5.689506e+06,5.587165e+06,5.689512e+06,5689512.0,5.689512e+06,5.689512e+06,5.689512e+06,5.689512e+06,5.689512e+06,5.689512e+06,5.689512e+06,5.689512e+06,5.689512e+06,5.689512e+06,5.689512e+06,5.689512e+06,5.689512e+06,5.689512e+06,5.689512e+06,5.689512e+06,5.689512e+06,5.689512e+06,5.602937e+06,5.602937e+06,5.594818e+06,5.594828e+06,5.591963e+06,5.591953e+06,5.689512e+06,5.586619e+06,5.586619e+06,5.586619e+06,5.689512e+06,5.689511e+06
mean,2018-07-25 09:00:40.515813,1.330341e+03,1.334473e+03,1.346201e+01,1.014888e+01,1.462641e+03,1.368363e+01,1.101716e+02,1.389089e+02,1.344377e+02,7.878012e+02,2018.0,2.765149e+00,7.290665e+00,1.577653e+01,3.942995e+00,1.983425e+04,2.638920e+03,1.998161e+04,2.638847e+03,1.271578e+04,1.271582e+06,3.177650e+04,2.666363e+01,5.520549e+01,1.271575e+04,1.271579e+06,3.177648e+04,2.666330e+01,5.520607e+01,1.877676e-01,5.733707e-02,1.704049e+01,1.357922e+03,1.458453e+03,7.364397e+00,1.482252e+03,5.416295e+00,1.948123e-01,-1.636356e-01,3.625993e+00,3.568496e-03
min,2018-01-01 00:00:00,1.000000e+00,1.000000e+00,0.000000e+00,-1.280000e+03,1.000000e+00,0.000000e+00,-1.244000e+03,-9.900000e+01,-1.228000e+03,1.600000e+01,2018.0,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.939300e+04,1.000000e+00,1.939300e+04,1.000000e+00,1.013500e+04,1.013505e+06,3.007000e+04,1.000000e+00,1.000000e+00,1.013500e+04,1.013505e+06,3.007000e+04,1.000000e+00,1.000000e+00,0.000000e+00,-2.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,-1.290000e+03,0.000000e+00,-2.000000e+00,1.000000e+00,0.000000e+00
25%,2018-04-22 00:00:00,9.150000e+02,9.160000e+02,0.000000e+00,-6.000000e+00,1.046000e+03,0.000000e+00,5.900000e+01,8.600000e+01,8.200000e+01,3.490000e+02,2018.0,2.000000e+00,4.000000e+00,8.000000e+00,2.000000e+00,1.969000e+04,9.420000e+02,1.968700e+04,9.420000e+02,1.129200e+04,1.129202e+06,3.072100e+04,1.200000e+01,3.400000e+01,1.129200e+04,1.129202e+06,3.072100e+04,1.200000e+01,3.400000e+01,0.000000e+00,-1.000000e+00,1.100000e+01,9.310000e+02,1.042000e+03,4.000000e+00,1.058000e+03,-1.400000e+01,0.000000e+00,-1.000000e+00,2.000000e+00,0.000000e+00
50%,2018-08-16 00:00:00,1.323000e+03,1.327000e+03,0.000000e+00,-2.000000e+00,1.503000e+03,0.000000e+00,9.200000e+01,1.200000e+02,1.170000e+02,6.280000e+02,2018.0,3.000000e+00,8.000000e+00,1.600000e+01,4.000000e+00,1.980500e+04,2.127000e+03,1.997700e+04,2.127000e+03,1.288900e+04,1.288903e+06,3.145400e+04,2.500000e+01,4.500000e+01,1.288900e+04,1.288903e+06,3.145400e+04,2.500000e+01,4.500000e+01,0.000000e+00,-1.000000e+00,1.400000e+01,1.341000e+03,1.500000e+03,6.000000e+00,1.512000e+03,-6.000000e+00,0.000000e+00,-1.000000e+00,3.000000e+00,0.000000e+00
75%,2018-10-25 00:00:00,1.735000e+03,1.745000e+03,7.000000e+00,7.000000e+00,1.915000e+03,8.000000e+00,1.390000e+02,1.700000e+02,1.650000e+02,1.024000e+03,2018.0,4.000000e+00,1.000000e+01,2.300000e+01,6.000000e+00,1.997700e+04,4.285000e+03,2.036800e+04,4.285000e+03,1.405700e+04,1.405702e+06,3.257500e+04,4.100000e+01,8.200000e+01,1.405700e+04,1.405702e+06,3.257500e+04,4.100000e+01,8.200000e+01,0.000000e+00,0.000000e+00,2.000000e+01,1.800000e+03,1.910000e+03,9.000000e+00,1.917000e+03,8.000000e+00,0.000000e+00,0.000000e+00,5.000000e+00,0.000000e+00
max,2018-12-31 00:00:00,2.359000e+03,2.400000e+03,2.625000e+03,2.625000e+03,2.400000e+03,2.635000e+03,6.960000e+02,1.645000e+03,7.570000e+02,4.983000e+03,2018.0,4.000000e+00,1.200000e+01,3.100000e+01,7.000000e+00,2.117100e+04,9.385000e+03,2.117100e+04,9.385000e+03,1.621800e+04,1.621802e+06,3.613300e+04,7.800000e+01,9.300000e+01,1.621800e+04,1.621802e+06,3.613300e+04,7.800000e+01,9.300000e+01,1.000000e+00,1.200000e+01,1.394000e+03,2.400000e+03,2.400000e+03,2.590000e+02,2.400000e+03,2.635000e+03,1.000000e+00,1.200000e+01,1.100000e+01,9.000000e+00
std,NaN,4.913570e+02,5.048563e+02,4.420411e+01,4.536897e+01,5.405804e+02,4.402848e+01,7.058990e+01,7.288408e+01,7.258416e+01,5.943094e+02,0.0,1.115764e+00,3.503684e+00,8.778083e+00,2.001097e+00,3.149599e+02,1.914474e+03,4.149514e+02,1.914574e+03,1.505246e+03,1.505245e+05,1.288216e+03,1.657312e+01,2.697075e+01,1.505254e+03,1.505252e+05,1.288178e+03,1.657323e+01,2.697067e+01,3.905265e-01,2.212210e+00,9.802525e+00,5.063342e+02,5.365503e+02,5.893011e+00,5.212881e+02,4.746066e+01,3.960562e-01,2.350674e+00,2.342451e+00,1.112816e-01

In [26]:
df[['Airline']].describe()

                       Airline
count                  5689512
unique                      28
top     Southwest Airlines Co.
freq                   1352552

In [27]:
df.shape

(5689512, 61)

In [28]:
df.shape, len(df)

((5689512, 61), 5689512)

Subsetting a Dataframe

In [29]:
df[['FlightDate', 'Airline', 'Origin']]

       FlightDate                      Airline Origin
0      2018-01-23            Endeavor Air Inc.    ABY
1      2018-01-24            Endeavor Air Inc.    ABY
2      2018-01-25            Endeavor Air Inc.    ABY
3      2018-01-26            Endeavor Air Inc.    ABY
4      2018-01-27            Endeavor Air Inc.    ABY
...           ...                          ...    ...
637609 2018-09-11  Air Wisconsin Airlines Corp    SCE
637610 2018-09-11  Air Wisconsin Airlines Corp    IAD
637611 2018-09-11  Air Wisconsin Airlines Corp    EVV
637612 2018-09-11  Air Wisconsin Airlines Corp    ORD
637613 2018-09-11  Air Wisconsin Airlines Corp    HPN

[5689512 rows x 3 columns]

In [30]:
df[df.columns[:5]]

       FlightDate                      Airline Origin Dest  Cancelled
0      2018-01-23            Endeavor Air Inc.    ABY  ATL      False
1      2018-01-24            Endeavor Air Inc.    ABY  ATL      False
2      2018-01-25            Endeavor Air Inc.    ABY  ATL      False
3      2018-01-26            Endeavor Air Inc.    ABY  ATL      False
4      2018-01-27            Endeavor Air Inc.    ABY  ATL      False
...           ...                          ...    ...  ...        ...
637609 2018-09-11  Air Wisconsin Airlines Corp    SCE  IAD      False
637610 2018-09-11  Air Wisconsin Airlines Corp    IAD  GSO      False
637611 2018-09-11  Air Wisconsin Airlines Corp    EVV  ORD      False
637612 2018-09-11  Air Wisconsin Airlines Corp    ORD  HPN      False
637613 2018-09-11  Air Wisconsin Airlines Corp    HPN  ORD      False

[5689512 rows x 5 columns]

In [31]:
df[df.columns[-5:]]

,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
0,0.0,-1.0,1300-1359,1,0.0
1,0.0,-1.0,1300-1359,1,0.0
2,0.0,-1.0,1300-1359,1,0.0
3,0.0,-1.0,1300-1359,1,0.0
4,0.0,-1.0,1500-1559,1,0.0
...,...,...,...,...,...
637609,0.0,-2.0,1500-1559,1,0.0
637610,0.0,-1.0,1300-1359,1,0.0
637611,0.0,-2.0,1200-1259,2,0.0
637612,0.0,-1.0,1700-1759,3,0.0
637613,0.0,-1.0,1900-1959,3,0.0

In [32]:
df[[c for c in df.columns if 'Time' in c]]

,CRSDepTime,DepTime,ArrTime,AirTime,CRSElapsedTime,ActualElapsedTime,DepTimeBlk,CRSArrTime,ArrTimeBlk
0,1202,1157.0,1256.0,38.0,62.0,59.0,1200-1259,1304,1300-1359
1,1202,1157.0,1258.0,36.0,62.0,61.0,1200-1259,1304,1300-1359
2,1202,1153.0,1302.0,40.0,62.0,69.0,1200-1259,1304,1300-1359
3,1202,1150.0,1253.0,35.0,62.0,63.0,1200-1259,1304,1300-1359
4,1400,1355.0,1459.0,36.0,60.0,64.0,1400-1459,1500,1500-1559
...,...,...,...,...,...,...,...,...,...
637609,1445,1433.0,1515.0,35.0,61.0,42.0,1400-1459,1546,1500-1559
637610,1235,1224.0,1344.0,43.0,80.0,80.0,1200-1259,1355,1300-1359
637611,1030,1016.0,1137.0,54.0,94.0,81.0,1000-1059,1204,1200-1259
637612,1410,1403.0,1717.0,104.0,136.0,134.0,1400-1459,1726,1700-1759
637613,1800,1754.0,1919.0,116.0,153.0,145.0,1800-1859,1933,1900-1959

In [33]:
df.select_dtypes('int')

,CRSDepTime,Year,Quarter,Month,DayofMonth,DayOfWeek,DOT_ID_Marketing_Airline,Flight_Number_Marketing_Airline,DOT_ID_Operating_Airline,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginStateFips,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestStateFips,DestWac,CRSArrTime,DistanceGroup
0,1202,2018,1,1,23,2,19790,3298,20363,3298,10146,1014602,30146,13,34,10397,1039707,30397,13,34,1304,1
1,1202,2018,1,1,24,3,19790,3298,20363,3298,10146,1014602,30146,13,34,10397,1039707,30397,13,34,1304,1
2,1202,2018,1,1,25,4,19790,3298,20363,3298,10146,1014602,30146,13,34,10397,1039707,30397,13,34,1304,1
3,1202,2018,1,1,26,5,19790,3298,20363,3298,10146,1014602,30146,13,34,10397,1039707,30397,13,34,1304,1
4,1400,2018,1,1,27,6,19790,3298,20363,3298,10146,1014602,30146,13,34,10397,1039707,30397,13,34,1500,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
637609,1445,2018,3,9,11,2,19977,3839,20046,3839,14711,1471105,34711,42,23,12264,1226402,30852,51,38,1546,1
637610,1235,2018,3,9,11,2,19977,3838,20046,3838,12264,1226402,30852,51,38,11995,1199502,31995,37,36,1355,1
637611,1030,2018,3,9,11,2,19977,3837,20046,3837,11612,1161206,31612,18,42,13930,1393006,30977,17,41,1204,2
637612,1410,2018,3,9,11,2,19977,3837,20046,3837,13930,1393006,30977,17,41,12197,1219702,31703,36,22,1726,3
637613,1800,2018,3,9,11,2,19977,3836,20046,3836,12197,1219702,31703,36,22,13930,1393006,30977,17,41,1933,3

In [34]:
df['Airline']

0                   Endeavor Air Inc.
1                   Endeavor Air Inc.
2                   Endeavor Air Inc.
3                   Endeavor Air Inc.
4                   Endeavor Air Inc.
                     ...
637609    Air Wisconsin Airlines Corp
637610    Air Wisconsin Airlines Corp
637611    Air Wisconsin Airlines Corp
637612    Air Wisconsin Airlines Corp
637613    Air Wisconsin Airlines Corp
Name: Airline, Length: 5689512, dtype: object

In [35]:
df[['Airline']]

                            Airline
0                 Endeavor Air Inc.
1                 Endeavor Air Inc.
2                 Endeavor Air Inc.
3                 Endeavor Air Inc.
4                 Endeavor Air Inc.
...                             ...
637609  Air Wisconsin Airlines Corp
637610  Air Wisconsin Airlines Corp
637611  Air Wisconsin Airlines Corp
637612  Air Wisconsin Airlines Corp
637613  Air Wisconsin Airlines Corp

[5689512 rows x 1 columns]

In [36]:
type(df[['Airline']])

pandas.core.frame.DataFrame

Filtering Rows using df.loc[] and df.iloc[]

In [37]:
df.iloc[1,3]

'ATL'

In [39]:
df.iloc[:5, :5]

  FlightDate            Airline Origin Dest  Cancelled
0 2018-01-23  Endeavor Air Inc.    ABY  ATL      False
1 2018-01-24  Endeavor Air Inc.    ABY  ATL      False
2 2018-01-25  Endeavor Air Inc.    ABY  ATL      False
3 2018-01-26  Endeavor Air Inc.    ABY  ATL      False
4 2018-01-27  Endeavor Air Inc.    ABY  ATL      False

In [40]:
df.iloc[5]

FlightDate            2018-01-28 00:00:00
Airline                 Endeavor Air Inc.
Origin                                ABY
Dest                                  ATL
Cancelled                           False
                             ...
ArrDel15                              1.0
ArrivalDelayGroups                    1.0
ArrTimeBlk                      1300-1359
DistanceGroup                           1
DivAirportLandings                    0.0
Name: 5, Length: 61, dtype: object

In [41]:
df.iloc[[5]]

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
5,2018-01-28,Endeavor Air Inc.,ABY,ATL,False,False,1202,1202.0,NaN,NaN,1326.0,22.0,37.0,62.0,84.0,145.0,2018,1,1,28,7,DL,DL_CODESHARE,19790,DL,3298,9E,20363,9E,N8918B,3298,10146,1014602,30146,"Albany, GA",GA,13,Georgia,34,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,NaN,NaN,1200-1259,34.0,1236.0,1313.0,13.0,1304,22.0,1.0,1.0,1300-1359,1,0.0

In [42]:
df.iloc[:,1]

0                   Endeavor Air Inc.
1                   Endeavor Air Inc.
2                   Endeavor Air Inc.
3                   Endeavor Air Inc.
4                   Endeavor Air Inc.
                     ...
637609    Air Wisconsin Airlines Corp
637610    Air Wisconsin Airlines Corp
637611    Air Wisconsin Airlines Corp
637612    Air Wisconsin Airlines Corp
637613    Air Wisconsin Airlines Corp
Name: Airline, Length: 5689512, dtype: object

In [43]:
df.iloc[:, [1,2]]

                            Airline Origin
0                 Endeavor Air Inc.    ABY
1                 Endeavor Air Inc.    ABY
2                 Endeavor Air Inc.    ABY
3                 Endeavor Air Inc.    ABY
4                 Endeavor Air Inc.    ABY
...                             ...    ...
637609  Air Wisconsin Airlines Corp    SCE
637610  Air Wisconsin Airlines Corp    IAD
637611  Air Wisconsin Airlines Corp    EVV
637612  Air Wisconsin Airlines Corp    ORD
637613  Air Wisconsin Airlines Corp    HPN

[5689512 rows x 2 columns]

In [44]:
df.loc[:, ['Airline', 'Origin']]

                            Airline Origin
0                 Endeavor Air Inc.    ABY
1                 Endeavor Air Inc.    ABY
2                 Endeavor Air Inc.    ABY
3                 Endeavor Air Inc.    ABY
4                 Endeavor Air Inc.    ABY
...                             ...    ...
637609  Air Wisconsin Airlines Corp    SCE
637610  Air Wisconsin Airlines Corp    IAD
637611  Air Wisconsin Airlines Corp    EVV
637612  Air Wisconsin Airlines Corp    ORD
637613  Air Wisconsin Airlines Corp    HPN

[5689512 rows x 2 columns]

In [45]:
#Filtering on Boolean expressions
df['Airline']=='Spirit Air Lines'

0         False
1         False
2         False
3         False
4         False
          ...
637609    False
637610    False
637611    False
637612    False
637613    False
Name: Airline, Length: 5689512, dtype: bool

In [46]:
df.loc[df['Airline']=='Spirit Air Lines']

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
22093,2018-01-06,Spirit Air Lines,ATL,IAH,False,False,640,638.0,0.0,-2.0,736.0,0.0,100.0,145.0,118.0,689.0,2018,1,1,6,6,NK,NK,20416,NK,363,NK,20416,NK,N672NK,363,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,12266,1226603,31453,"Houston, TX",TX,48,Texas,74,0.0,-1.0,0600-0659,11.0,649.0,729.0,7.0,805,-29.0,0.0,-2.0,0800-0859,3,0.0
22094,2018-01-07,Spirit Air Lines,ATL,IAH,False,False,640,637.0,0.0,-3.0,749.0,0.0,108.0,145.0,132.0,689.0,2018,1,1,7,7,NK,NK,20416,NK,363,NK,20416,NK,N665NK,363,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,12266,1226603,31453,"Houston, TX",TX,48,Texas,74,0.0,-1.0,0600-0659,10.0,647.0,735.0,14.0,805,-16.0,0.0,-2.0,0800-0859,3,0.0
22095,2018-01-08,Spirit Air Lines,ATL,IAH,False,False,640,655.0,15.0,15.0,801.0,0.0,107.0,145.0,126.0,689.0,2018,1,1,8,1,NK,NK,20416,NK,363,NK,20416,NK,N657NK,363,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,12266,1226603,31453,"Houston, TX",TX,48,Texas,74,1.0,1.0,0600-0659,12.0,707.0,754.0,7.0,805,-4.0,0.0,-1.0,0800-0859,3,0.0
22096,2018-01-09,Spirit Air Lines,ATL,IAH,False,False,640,635.0,0.0,-5.0,727.0,0.0,93.0,145.0,112.0,689.0,2018,1,1,9,2,NK,NK,20416,NK,363,NK,20416,NK,N672NK,363,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,12266,1226603,31453,"Houston, TX",TX,48,Texas,74,0.0,-1.0,0600-0659,12.0,647.0,720.0,7.0,805,-38.0,0.0,-2.0,0800-0859,3,0.0
22097,2018-01-10,Spirit Air Lines,ATL,IAH,False,False,640,639.0,0.0,-1.0,741.0,0.0,101.0,145.0,122.0,689.0,2018,1,1,10,3,NK,NK,20416,NK,363,NK,20416,NK,N673NK,363,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,12266,1226603,31453,"Houston, TX",TX,48,Texas,74,0.0,-1.0,0600-0659,14.0,653.0,734.0,7.0,805,-24.0,0.0,-2.0,0800-0859,3,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501673,2018-09-11,Spirit Air Lines,DTW,ATL,False,False,610,608.0,0.0,-2.0,803.0,0.0,94.0,124.0,115.0,594.0,2018,3,9,11,2,NK,NK,20416,NK,1565,NK,20416,NK,N620NK,1565,11433,1143302,31295,"Detroit, MI",MI,26,Michigan,43,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,0.0,-1.0,0600-0659,13.0,621.0,755.0,8.0,814,-11.0,0.0,-1.0,0800-0859,3,0.0
501674,2018-09-12,Spirit Air Lines,DTW,ATL,False,False,610,611.0,1.0,1.0,818.0,4.0,103.0,124.0,127.0,594.0,2018,3,9,12,3,NK,NK,20416,NK,1565,NK,20416,NK,N616NK,1565,11433,1143302,31295,"Detroit, MI",MI,26,Michigan,43,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,0.0,0.0,0600-0659,15.0,626.0,809.0,9.0,814,4.0,0.0,0.0,0800-0859,3,0.0
501675,2018-09-18,Spirit Air Lines,DTW,ATL,False,False,610,606.0,0.0,-4.0,756.0,0.0,89.0,124.0,110.0,594.0,2018,3,9,18,2,NK,NK,20416,NK,1565,NK,20416,NK,N903NK,1565,11433,1143302,31295,"Detroit, MI",MI,26,Michigan,43,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,0.0,-1.0,0600-0659,12.0,618.0,747.0,9.0,814,-18.0,0.0,-2.0,0800-0859,3,0.0
501676,2018-09-19,Spirit Air Lines,DTW,ATL,False,False,610,605.0,0.0,-5.0,758.0,0.0,89.0,124.0,113.0,594.0,2018,3,9,19,3,NK,NK,20416,NK,1565,NK,20416,NK,N624NK,1565,11433,1143302,31295,"Detroit, MI",MI,26,Michigan,43,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,0.0,-1.0,0600-0659,15.0,620.0,749.0,9.0,814,-16.0,0.0,-2.0,0800-0859,3,0.0
501677,2018-09-25,Spirit Air Lines,DTW,ATL,False,False,610,607.0,0.0,-3.0,758.0,0.0,93.0,124.0,111.0,594.0,2018,3,9,25,2,NK,NK,20416,NK,1565,NK,20416,NK,N628NK,1565,11433,1143302,31295,"Detroit, MI",MI,26,Michigan,43,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,0.0,-1.0,0600-0659,12.0,619.0,752.0,6.0,814,-16.0,0.0,-2.0,0800-0859,3,0.0

In [48]:
df.loc[(df['Airline']=='Spirit Air Lines') & (df['FlightDate']=='2018-09-09')]

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
152110,2018-09-09,Spirit Air Lines,MCO,CLE,False,False,1050,1034.0,0.0,-16.0,1249.0,0.0,110.0,146.0,135.0,895.0,2018,3,9,9,7,NK,NK,20416,NK,534,NK,20416,NK,N617NK,534,13204,1320402,31454,"Orlando, FL",FL,12,Florida,33,11042,1104205,30647,"Cleveland, OH",OH,39,Ohio,44,0.0,-2.0,1000-1059,16.0,1050.0,1240.0,9.0,1316,-27.0,0.0,-2.0,1300-1359,4,0.0
152140,2018-09-09,Spirit Air Lines,CLE,MCO,False,False,800,819.0,19.0,19.0,1045.0,14.0,121.0,151.0,146.0,895.0,2018,3,9,9,7,NK,NK,20416,NK,535,NK,20416,NK,N644NK,535,11042,1104205,30647,"Cleveland, OH",OH,39,Ohio,44,13204,1320402,31454,"Orlando, FL",FL,12,Florida,33,1.0,1.0,0800-0859,16.0,835.0,1036.0,9.0,1031,14.0,0.0,0.0,1000-1059,4,0.0
152170,2018-09-09,Spirit Air Lines,FLL,ATL,False,True,1125,1115.0,0.0,-10.0,1540.0,NaN,NaN,116.0,NaN,581.0,2018,3,9,9,7,NK,NK,20416,NK,536,NK,20416,NK,N536NK,536,11697,1169706,32467,"Fort Lauderdale, FL",FL,12,Florida,33,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,0.0,-1.0,1100-1159,17.0,1132.0,1527.0,13.0,1321,NaN,NaN,NaN,1300-1359,3,1.0
152194,2018-09-09,Spirit Air Lines,LAS,PDX,False,False,2215,2210.0,0.0,-5.0,20.0,0.0,112.0,142.0,130.0,763.0,2018,3,9,9,7,NK,NK,20416,NK,546,NK,20416,NK,N651NK,546,12889,1288903,32211,"Las Vegas, NV",NV,32,Nevada,85,14057,1405702,34057,"Portland, OR",OR,41,Oregon,92,0.0,-1.0,2200-2259,12.0,2222.0,14.0,6.0,37,-17.0,0.0,-2.0,0001-0559,4,0.0
152218,2018-09-09,Spirit Air Lines,BWI,MYR,False,False,1042,1054.0,12.0,12.0,1210.0,6.0,60.0,82.0,76.0,399.0,2018,3,9,9,7,NK,NK,20416,NK,547,NK,20416,NK,N623NK,547,10821,1082106,30852,"Baltimore, MD",MD,24,Maryland,35,13577,1357702,31135,"Myrtle Beach, SC",SC,45,South Carolina,37,0.0,0.0,1000-1059,11.0,1105.0,1205.0,5.0,1204,6.0,0.0,0.0,1200-1259,2,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501586,2018-09-09,Spirit Air Lines,MYR,PIT,False,False,1105,1059.0,0.0,-6.0,1228.0,0.0,70.0,90.0,89.0,475.0,2018,3,9,9,7,NK,NK,20416,NK,1477,NK,20416,NK,N901NK,1477,13577,1357702,31135,"Myrtle Beach, SC",SC,45,South Carolina,37,14122,1412202,30198,"Pittsburgh, PA",PA,42,Pennsylvania,23,0.0,-1.0,1100-1159,12.0,1111.0,1221.0,7.0,1235,-7.0,0.0,-1.0,1200-1259,2,0.0
501601,2018-09-09,Spirit Air Lines,EWR,MCO,False,False,1015,1010.0,0.0,-5.0,1247.0,0.0,127.0,168.0,157.0,937.0,2018,3,9,9,7,NK,NK,20416,NK,149,NK,20416,NK,N684NK,149,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,13204,1320402,31454,"Orlando, FL",FL,12,Florida,33,0.0,-1.0,1000-1059,21.0,1031.0,1238.0,9.0,1303,-16.0,0.0,-2.0,1300-1359,4,0.0
501631,2018-09-09,Spirit Air Lines,MCO,EWR,False,False,2020,2149.0,89.0,89.0,9.0,71.0,119.0,158.0,140.0,937.0,2018,3,9,9,7,NK,NK,20416,NK,150,NK,20416,NK,N603NK,150,13204,1320402,31454,"Orlando, FL",FL,12,Florida,33,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,1.0,5.0,2000-2059,12.0,2201.0,2400.0,9.0,2258,71.0,1.0,4.0,2200-2259,4,0.0
501658,2018-09-09,Spirit Air Lines,MCO,CLE,False,False,1700,1655.0,0.0,-5.0,1914.0,0.0,115.0,148.0,139.0,895.0,2018,3,9,9,7,NK,NK,20416,NK,1536,NK,20416,NK,N656NK,1536,13204,1320402,31454,"Orlando, FL",FL,12,Florida,33,11042,1104205,30647,"Cleveland, OH",OH,39,Ohio,44,0.0,-1.0,1700-1759,16.0,1711.0,1906.0,8.0,1928,-14.0,0.0,-1.0,1900-1959,4,0.0
501666,2018-09-09,Spirit Air Lines,CLE,MCO,False,False,1331,1324.0,0.0,-7.0,1549.0,0.0,122.0,149.0,145.0,895.0,2018,3,9,9,7,NK,NK,20416,NK,1537,NK,20416,NK,N902NK,1537,11042,1104205,30647,"Cleveland, OH",OH,39,Ohio,44,13204,1320402,31454,"Orlando, FL",FL,12,Florida,33,0.0,-1.0,1300-1359,16.0,1340.0,1542.0,7.0,1600,-11.0,0.0,-1.0,1600-1659,4,0.0

In [50]:
#Inverse of Boolean expression
~((df['Airline']=='Spirit Air Lines') & (df['FlightDate']=='2018-09-09'))

0         True
1         True
2         True
3         True
4         True
          ...
637609    True
637610    True
637611    True
637612    True
637613    True
Length: 5689512, dtype: bool

In [51]:
df.loc[~((df['Airline']=='Spirit Air Lines') & (df['FlightDate']=='2018-09-09'))]

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
0,2018-01-23,Endeavor Air Inc.,ABY,ATL,False,False,1202,1157.0,0.0,-5.0,1256.0,0.0,38.0,62.0,59.0,145.0,2018,1,1,23,2,DL,DL_CODESHARE,19790,DL,3298,9E,20363,9E,N8928A,3298,10146,1014602,30146,"Albany, GA",GA,13,Georgia,34,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,0.0,-1.0,1200-1259,14.0,1211.0,1249.0,7.0,1304,-8.0,0.0,-1.0,1300-1359,1,0.0
1,2018-01-24,Endeavor Air Inc.,ABY,ATL,False,False,1202,1157.0,0.0,-5.0,1258.0,0.0,36.0,62.0,61.0,145.0,2018,1,1,24,3,DL,DL_CODESHARE,19790,DL,3298,9E,20363,9E,N800AY,3298,10146,1014602,30146,"Albany, GA",GA,13,Georgia,34,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,0.0,-1.0,1200-1259,13.0,1210.0,1246.0,12.0,1304,-6.0,0.0,-1.0,1300-1359,1,0.0
2,2018-01-25,Endeavor Air Inc.,ABY,ATL,False,False,1202,1153.0,0.0,-9.0,1302.0,0.0,40.0,62.0,69.0,145.0,2018,1,1,25,4,DL,DL_CODESHARE,19790,DL,3298,9E,20363,9E,N8836A,3298,10146,1014602,30146,"Albany, GA",GA,13,Georgia,34,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,0.0,-1.0,1200-1259,18.0,1211.0,1251.0,11.0,1304,-2.0,0.0,-1.0,1300-1359,1,0.0
3,2018-01-26,Endeavor Air Inc.,ABY,ATL,False,False,1202,1150.0,0.0,-12.0,1253.0,0.0,35.0,62.0,63.0,145.0,2018,1,1,26,5,DL,DL_CODESHARE,19790,DL,3298,9E,20363,9E,N800AY,3298,10146,1014602,30146,"Albany, GA",GA,13,Georgia,34,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,0.0,-1.0,1200-1259,17.0,1207.0,1242.0,11.0,1304,-11.0,0.0,-1.0,1300-1359,1,0.0
4,2018-01-27,Endeavor Air Inc.,ABY,ATL,False,False,1400,1355.0,0.0,-5.0,1459.0,0.0,36.0,60.0,64.0,145.0,2018,1,1,27,6,DL,DL_CODESHARE,19790,DL,3298,9E,20363,9E,N8839E,3298,10146,1014602,30146,"Albany, GA",GA,13,Georgia,34,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,0.0,-1.0,1400-1459,17.0,1412.0,1448.0,11.0,1500,-1.0,0.0,-1.0,1500-1559,1,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
637609,2018-09-11,Air Wisconsin Airlines Corp,SCE,IAD,False,False,1445,1433.0,0.0,-12.0,1515.0,0.0,35.0,61.0,42.0,133.0,2018,3,9,11,2,UA,UA_CODESHARE,19977,UA,3839,ZW,20046,ZW,N437AW,3839,14711,1471105,34711,"State College, PA",PA,42,Pennsylvania,23,12264,1226402,30852,"Washington, DC",VA,51,Virginia,38,0.0,-1.0,1400-1459,4.0,1437.0,1512.0,3.0,1546,-31.0,0.0,-2.0,1500-1559,1,0.0
637610,2018-09-11,Air Wisconsin Airlines Corp,IAD,GSO,False,False,1235,1224.0,0.0,-11.0,1344.0,0.0,43.0,80.0,80.0,239.0,2018,3,9,11,2,UA,UA_CODESHARE,19977,UA,3838,ZW,20046,ZW,N410AW,3838,12264,1226402,30852,"Washington, DC",VA,51,Virginia,38,11995,1199502,31995,"Greensboro/High Point, NC",NC,37,North Carolina,36,0.0,-1.0,1200-1259,30.0,1254.0,1337.0,7.0,1355,-11.0,0.0,-1.0,1300-1359,1,0.0
637611,2018-09-11,Air Wisconsin Airlines Corp,EVV,ORD,False,False,1030,1016.0,0.0,-14.0,1137.0,0.0,54.0,94.0,81.0,272.0,2018,3,9,11,2,UA,UA_CODESHARE,19977,UA,3837,ZW,20046,ZW,N467AW,3837,11612,1161206,31612,"Evansville, IN",IN,18,Indiana,42,13930,1393006,30977,"Chicago, IL",IL,17,Illinois,41,0.0,-1.0,1000-1059,20.0,1036.0,1130.0,7.0,1204,-27.0,0.0,-2.0,1200-1259,2,0.0
637612,2018-09-11,Air Wisconsin Airlines Corp,ORD,HPN,False,False,1410,1403.0,0.0,-7.0,1717.0,0.0,104.0,136.0,134.0,738.0,2018,3,9,11,2,UA,UA_CODESHARE,19977,UA,3837,ZW,20046,ZW,N440AW,3837,13930,1393006,30977,"Chicago, IL",IL,17,Illinois,41,12197,1219702,31703,"White Plains, NY",NY,36,New York,22,0.0,-1.0,1400-1459,25.0,1428.0,1712.0,5.0,1726,-9.0,0.0,-1.0,1700-1759,3,0.0
637613,2018-09-11,Air Wisconsin Airlines Corp,HPN,ORD,False,False,1800,1754.0,0.0,-6.0,1919.0,0.0,116.0,153.0,145.0,738.0,2018,3,9,11,2,UA,UA_CODESHARE,19977,UA,3836,ZW,20046,ZW,N440AW,3836,12197,1219702,31703,"White Plains, NY",NY,36,New York,22,13930,1393006,30977,"Chicago, IL",IL,17,Illinois,41,0.0,-1.0,1800-1859,14.0,1808.0,1904.0,15.0,1933,-14.0,0.0,-1.0,1900-1959,3,0.0

Filtering Using Query

In [53]:
df.query('(DepTime>1130) and (Origin=="DRO")')

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
24675,2018-01-19,SkyWest Airlines Inc.,DRO,DEN,False,False,1805,1742.0,0.0,-23.0,1912.0,0.0,44.0,77.0,90.0,250.0,2018,1,1,19,5,UA,UA_CODESHARE,19977,UA,5401,OO,20304,OO,N901EV,5401,11413,1141306,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-2.0,1800-1859,12.0,1754.0,1838.0,34.0,1922,-10.0,0.0,-1.0,1900-1959,2,0.0
24720,2018-01-19,SkyWest Airlines Inc.,DRO,DEN,False,False,1545,1529.0,0.0,-16.0,1634.0,0.0,41.0,70.0,65.0,250.0,2018,1,1,19,5,UA,UA_CODESHARE,19977,UA,5447,OO,20304,OO,N701BR,5447,11413,1141306,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-2.0,1500-1559,15.0,1544.0,1625.0,9.0,1655,-21.0,0.0,-2.0,1600-1659,2,0.0
24991,2018-01-19,SkyWest Airlines Inc.,DRO,DEN,False,False,1330,1321.0,0.0,-9.0,1427.0,0.0,46.0,69.0,66.0,250.0,2018,1,1,19,5,UA,UA_CODESHARE,19977,UA,5801,OO,20304,OO,N916SW,5801,11413,1141306,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1300-1359,12.0,1333.0,1419.0,8.0,1439,-12.0,0.0,-1.0,1400-1459,2,0.0
27338,2018-01-05,SkyWest Airlines Inc.,DRO,DEN,False,False,1805,1747.0,0.0,-18.0,1857.0,0.0,44.0,75.0,70.0,250.0,2018,1,1,5,5,UA,UA_CODESHARE,19977,UA,5401,OO,20304,OO,N928EV,5401,11413,1141306,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-2.0,1800-1859,14.0,1801.0,1845.0,12.0,1920,-23.0,0.0,-2.0,1900-1959,2,0.0
27380,2018-01-05,SkyWest Airlines Inc.,DRO,DEN,False,False,1550,1539.0,0.0,-11.0,1641.0,0.0,45.0,69.0,62.0,250.0,2018,1,1,5,5,UA,UA_CODESHARE,19977,UA,5447,OO,20304,OO,N970SW,5447,11413,1141306,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1500-1559,10.0,1549.0,1634.0,7.0,1659,-18.0,0.0,-2.0,1600-1659,2,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
524708,2018-09-14,SkyWest Airlines Inc.,DRO,DEN,False,False,1551,1545.0,0.0,-6.0,1651.0,0.0,47.0,69.0,66.0,250.0,2018,3,9,14,5,UA,UA_CODESHARE,19977,UA,5447,OO,20304,OO,N204SY,5447,11413,1141306,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1500-1559,13.0,1558.0,1645.0,6.0,1700,-9.0,0.0,-1.0,1700-1759,2,0.0
526482,2018-09-15,SkyWest Airlines Inc.,DRO,DEN,False,False,1551,1550.0,0.0,-1.0,1659.0,0.0,47.0,69.0,69.0,250.0,2018,3,9,15,6,UA,UA_CODESHARE,19977,UA,5447,OO,20304,OO,N154SY,5447,11413,1141306,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1500-1559,13.0,1603.0,1650.0,9.0,1700,-1.0,0.0,-1.0,1700-1759,2,0.0
637259,2018-09-11,Trans States Airlines,DRO,DEN,False,False,1551,1543.0,0.0,-8.0,1650.0,0.0,49.0,69.0,67.0,250.0,2018,3,9,11,2,UA,UA_CODESHARE,19977,UA,4744,AX,20237,AX,N17138,4744,11413,1141306,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1500-1559,11.0,1554.0,1643.0,7.0,1700,-10.0,0.0,-1.0,1700-1759,2,0.0
637267,2018-09-11,Trans States Airlines,DRO,DEN,False,False,1750,1745.0,0.0,-5.0,1858.0,0.0,50.0,76.0,73.0,250.0,2018,3,9,11,2,UA,UA_CODESHARE,19977,UA,4733,AX,20237,AX,N41104,4733,11413,1141306,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1700-1759,12.0,1757.0,1847.0,11.0,1906,-8.0,0.0,-1.0,1900-1959,2,0.0
637360,2018-09-11,Trans States Airlines,DRO,DEN,False,False,1310,1302.0,0.0,-8.0,1400.0,0.0,46.0,70.0,58.0,250.0,2018,3,9,11,2,UA,UA_CODESHARE,19977,UA,4633,AX,20237,AX,N21130,4633,11413,1141306,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1300-1359,9.0,1311.0,1357.0,3.0,1420,-20.0,0.0,-2.0,1400-1459,2,0.0

In [55]:
min_time=1130
df.query('(DepTime>=@min_time) and (Origin=="DRO")')

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
24675,2018-01-19,SkyWest Airlines Inc.,DRO,DEN,False,False,1805,1742.0,0.0,-23.0,1912.0,0.0,44.0,77.0,90.0,250.0,2018,1,1,19,5,UA,UA_CODESHARE,19977,UA,5401,OO,20304,OO,N901EV,5401,11413,1141306,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-2.0,1800-1859,12.0,1754.0,1838.0,34.0,1922,-10.0,0.0,-1.0,1900-1959,2,0.0
24720,2018-01-19,SkyWest Airlines Inc.,DRO,DEN,False,False,1545,1529.0,0.0,-16.0,1634.0,0.0,41.0,70.0,65.0,250.0,2018,1,1,19,5,UA,UA_CODESHARE,19977,UA,5447,OO,20304,OO,N701BR,5447,11413,1141306,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-2.0,1500-1559,15.0,1544.0,1625.0,9.0,1655,-21.0,0.0,-2.0,1600-1659,2,0.0
24991,2018-01-19,SkyWest Airlines Inc.,DRO,DEN,False,False,1330,1321.0,0.0,-9.0,1427.0,0.0,46.0,69.0,66.0,250.0,2018,1,1,19,5,UA,UA_CODESHARE,19977,UA,5801,OO,20304,OO,N916SW,5801,11413,1141306,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1300-1359,12.0,1333.0,1419.0,8.0,1439,-12.0,0.0,-1.0,1400-1459,2,0.0
27338,2018-01-05,SkyWest Airlines Inc.,DRO,DEN,False,False,1805,1747.0,0.0,-18.0,1857.0,0.0,44.0,75.0,70.0,250.0,2018,1,1,5,5,UA,UA_CODESHARE,19977,UA,5401,OO,20304,OO,N928EV,5401,11413,1141306,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-2.0,1800-1859,14.0,1801.0,1845.0,12.0,1920,-23.0,0.0,-2.0,1900-1959,2,0.0
27380,2018-01-05,SkyWest Airlines Inc.,DRO,DEN,False,False,1550,1539.0,0.0,-11.0,1641.0,0.0,45.0,69.0,62.0,250.0,2018,1,1,5,5,UA,UA_CODESHARE,19977,UA,5447,OO,20304,OO,N970SW,5447,11413,1141306,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1500-1559,10.0,1549.0,1634.0,7.0,1659,-18.0,0.0,-2.0,1600-1659,2,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
524708,2018-09-14,SkyWest Airlines Inc.,DRO,DEN,False,False,1551,1545.0,0.0,-6.0,1651.0,0.0,47.0,69.0,66.0,250.0,2018,3,9,14,5,UA,UA_CODESHARE,19977,UA,5447,OO,20304,OO,N204SY,5447,11413,1141306,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1500-1559,13.0,1558.0,1645.0,6.0,1700,-9.0,0.0,-1.0,1700-1759,2,0.0
526482,2018-09-15,SkyWest Airlines Inc.,DRO,DEN,False,False,1551,1550.0,0.0,-1.0,1659.0,0.0,47.0,69.0,69.0,250.0,2018,3,9,15,6,UA,UA_CODESHARE,19977,UA,5447,OO,20304,OO,N154SY,5447,11413,1141306,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1500-1559,13.0,1603.0,1650.0,9.0,1700,-1.0,0.0,-1.0,1700-1759,2,0.0
637259,2018-09-11,Trans States Airlines,DRO,DEN,False,False,1551,1543.0,0.0,-8.0,1650.0,0.0,49.0,69.0,67.0,250.0,2018,3,9,11,2,UA,UA_CODESHARE,19977,UA,4744,AX,20237,AX,N17138,4744,11413,1141306,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1500-1559,11.0,1554.0,1643.0,7.0,1700,-10.0,0.0,-1.0,1700-1759,2,0.0
637267,2018-09-11,Trans States Airlines,DRO,DEN,False,False,1750,1745.0,0.0,-5.0,1858.0,0.0,50.0,76.0,73.0,250.0,2018,3,9,11,2,UA,UA_CODESHARE,19977,UA,4733,AX,20237,AX,N41104,4733,11413,1141306,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1700-1759,12.0,1757.0,1847.0,11.0,1906,-8.0,0.0,-1.0,1900-1959,2,0.0
637360,2018-09-11,Trans States Airlines,DRO,DEN,False,False,1310,1302.0,0.0,-8.0,1400.0,0.0,46.0,70.0,58.0,250.0,2018,3,9,11,2,UA,UA_CODESHARE,19977,UA,4633,AX,20237,AX,N21130,4633,11413,1141306,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1300-1359,9.0,1311.0,1357.0,3.0,1420,-20.0,0.0,-2.0,1400-1459,2,0.0

Summarizing Data

In [56]:
df['DepTime'].mean()

1334.4728214824347

In [57]:
df['DepTime'].min()

1.0

In [58]:
df['DepTime'].max()

2400.0

In [59]:
df['DepTime'].std()

504.85629665034406

In [62]:
df['DepTime'].var()

254879.8802675002

In [63]:
df['DepTime'].count()

5604132

In [64]:
df['DepTime'].sum()

7478561842.0

In [65]:
df['DepTime'].quantile(0.5)

1327.0

In [67]:
df['DepTime'].quantile([0.25,0.75])

0.25     916.0
0.75    1745.0
Name: DepTime, dtype: float64

In [68]:
df[['DepTime','DepDelay', 'ArrTime', 'ArrDelay']].mean()

DepTime     1334.472821
DepDelay      10.148876
ArrTime     1462.641310
ArrDelay       5.416295
dtype: float64

In [69]:
df[['DepTime','DepDelay','ArrTime','ArrDelay']].agg(['mean','min','max'])

          DepTime     DepDelay     ArrTime     ArrDelay
mean  1334.472821    10.148876  1462.64131     5.416295
min      1.000000 -1280.000000     1.00000 -1290.000000
max   2400.000000  2625.000000  2400.00000  2635.000000

In [70]:
df[['DepTime','DepDelay','ArrTime','ArrDelay']].agg(
    {
        'DepTime':['min','max'],
        'DepDelay':['mean'],
        'ArrTime':['min','max']
    }
)

      DepTime   DepDelay  ArrTime
min       1.0        NaN      1.0
max    2400.0        NaN   2400.0
mean      NaN  10.148876      NaN

Summarizing Categorical Variables

In [71]:
df['Airline'].unique()

array(['Endeavor Air Inc.', 'JetBlue Airways', 'ExpressJet Airlines Inc.',
       'Allegiant Air', 'Hawaiian Airlines Inc.', 'Spirit Air Lines',
       'SkyWest Airlines Inc.', 'Frontier Airlines Inc.',
       'Empire Airlines Inc.', 'Southwest Airlines Co.',
       'Mesa Airlines Inc.', 'Republic Airlines', 'Delta Air Lines Inc.',
       'United Air Lines Inc.', 'Alaska Airlines Inc.', 'Horizon Air',
       'Commutair Aka Champlain Enterprises, Inc.',
       'Trans States Airlines',
       'GoJet Airlines, LLC d/b/a United Express',
       'Air Wisconsin Airlines Corp', 'Cape Air', 'Compass Airlines',
       'Virgin America', 'Peninsula Airways Inc.', 'Envoy Air',
       'American Airlines Inc.', 'Comair Inc.',
       'Capital Cargo International'], dtype=object)

In [72]:
df['Airline'].nunique()

28

In [73]:
df['Airline'].value_counts()

Airline
Southwest Airlines Co.                       1352552
United Air Lines Inc.                         621565
SkyWest Airlines Inc.                         531792
Delta Air Lines Inc.                          461718
American Airlines Inc.                        385183
JetBlue Airways                               305010
Republic Airlines                             203529
Alaska Airlines Inc.                          184751
Spirit Air Lines                              176178
ExpressJet Airlines Inc.                      167180
Mesa Airlines Inc.                            153697
Envoy Air                                     127750
Frontier Airlines Inc.                        120035
Endeavor Air Inc.                             120030
Comair Inc.                                   117132
Air Wisconsin Airlines Corp                    98763
Allegiant Air                                  96221
Horizon Air                                    85245
Hawaiian Airlines Inc.                         83723
Trans States Airlines                          66885
GoJet Airlines, LLC d/b/a United Express       63498
Commutair Aka Champlain Enterprises, Inc.      48010
Compass Airlines                               44898
Capital Cargo International                    44440
Virgin America                                 17670
Empire Airlines Inc.                            9087
Cape Air                                        1661
Peninsula Airways Inc.                          1309
Name: count, dtype: int64

In [75]:
df['Airline'].value_counts(normalize=True)

Airline
Southwest Airlines Co.                       0.237727
United Air Lines Inc.                        0.109248
SkyWest Airlines Inc.                        0.093469
Delta Air Lines Inc.                         0.081152
American Airlines Inc.                       0.067701
JetBlue Airways                              0.053609
Republic Airlines                            0.035773
Alaska Airlines Inc.                         0.032472
Spirit Air Lines                             0.030965
ExpressJet Airlines Inc.                     0.029384
Mesa Airlines Inc.                           0.027014
Envoy Air                                    0.022454
Frontier Airlines Inc.                       0.021098
Endeavor Air Inc.                            0.021097
Comair Inc.                                  0.020587
Air Wisconsin Airlines Corp                  0.017359
Allegiant Air                                0.016912
Horizon Air                                  0.014983
Hawaiian Airlines Inc.                       0.014715
Trans States Airlines                        0.011756
GoJet Airlines, LLC d/b/a United Express     0.011161
Commutair Aka Champlain Enterprises, Inc.    0.008438
Compass Airlines                             0.007891
Capital Cargo International                  0.007811
Virgin America                               0.003106
Empire Airlines Inc.                         0.001597
Cape Air                                     0.000292
Peninsula Airways Inc.                       0.000230
Name: proportion, dtype: float64

In [76]:
df[['Airline', 'Origin']].value_counts()

Airline                                   Origin
Delta Air Lines Inc.                      ATL       119934
Southwest Airlines Co.                    MDW        82216
United Air Lines Inc.                     ORD        77418
Southwest Airlines Co.                    LAS        73419
                                          BWI        72226
                                                     ...
Allegiant Air                             BHM            1
GoJet Airlines, LLC d/b/a United Express  CAK            1
Compass Airlines                          IDA            1
Capital Cargo International               PIT            1
Trans States Airlines                     ORF            1
Name: count, Length: 2439, dtype: int64

In [77]:
df[['Airline', 'Origin']].value_counts().reset_index()

                                       Airline Origin   count
0                         Delta Air Lines Inc.    ATL  119934
1                       Southwest Airlines Co.    MDW   82216
2                        United Air Lines Inc.    ORD   77418
3                       Southwest Airlines Co.    LAS   73419
4                       Southwest Airlines Co.    BWI   72226
...                                        ...    ...     ...
2434                             Allegiant Air    BHM       1
2435  GoJet Airlines, LLC d/b/a United Express    CAK       1
2436                          Compass Airlines    IDA       1
2437               Capital Cargo International    PIT       1
2438                     Trans States Airlines    ORF       1

[2439 rows x 3 columns]

Advanced Column Methods

In [78]:
df[['CRSDepTime']].rank()

        CRSDepTime
0        2396362.5
1        2396362.5
2        2396362.5
3        2396362.5
4        3047844.0
...            ...
637609   3303880.5
637610   2578843.0
637611   1859594.0
637612   3104810.5
637613   4427375.5

[5689512 rows x 1 columns]

In [79]:
df[['CRSDepTime']].rank(method='dense')

        CRSDepTime
0            649.0
1            649.0
2            649.0
3            649.0
4            767.0
...            ...
637609       812.0
637610       682.0
637611       557.0
637612       777.0
637613      1007.0

[5689512 rows x 1 columns]

In [80]:
df[['CRSDepTime']].rank(method='first')

        CRSDepTime
0        2394956.0
1        2394957.0
2        2394958.0
3        2394959.0
4        3032667.0
...            ...
637609   3313935.0
637610   2587935.0
637611   1870377.0
637612   3112935.0
637613   4440018.0

[5689512 rows x 1 columns]

In [81]:
df[['CRSDepTime']].shift(1)

        CRSDepTime
0              NaN
1           1202.0
2           1202.0
3           1202.0
4           1202.0
...            ...
637609      1400.0
637610      1445.0
637611      1235.0
637612      1030.0
637613      1410.0

[5689512 rows x 1 columns]

In [82]:
df[['CRSDepTime']].shift(3)

        CRSDepTime
0              NaN
1              NaN
2              NaN
3           1202.0
4           1202.0
...            ...
637609      2012.0
637610      1445.0
637611      1400.0
637612      1445.0
637613      1235.0

[5689512 rows x 1 columns]

In [83]:
df[['CRSDepTime']].shift(3, fill_value=0)

        CRSDepTime
0                0
1                0
2                0
3             1202
4             1202
...            ...
637609        2012
637610        1445
637611        1400
637612        1445
637613        1235

[5689512 rows x 1 columns]

In [84]:
df[['CRSDepTime']].cumsum()

        CRSDepTime
0             1202
1             2404
2             3606
3             4808
4             6208
...            ...
637609  7568987628
637610  7568988863
637611  7568989893
637612  7568991303
637613  7568993103

[5689512 rows x 1 columns]

In [85]:
df[['CRSDepTime']].cummax()

        CRSDepTime
0             1202
1             1202
2             1202
3             1202
4             1400
...            ...
637609        2359
637610        2359
637611        2359
637612        2359
637613        2359

[5689512 rows x 1 columns]

In [86]:
df[['CRSDepTime']].cummin()

        CRSDepTime
0             1202
1             1202
2             1202
3             1202
4             1202
...            ...
637609           1
637610           1
637611           1
637612           1
637613           1

[5689512 rows x 1 columns]

Rolling methods helpful for the Time Series Data

In [87]:
df[['DepDelayMinutes']].rolling(window=5)

Rolling [window=5,center=False,axis=0,method=single]

In [88]:
df[['DepDelayMinutes']].rolling(window=5).mean()

        DepDelayMinutes
0                   NaN
1                   NaN
2                   NaN
3                   NaN
4                   0.0
...                 ...
637609              0.0
637610              0.0
637611              0.0
637612              0.0
637613              0.0

[5689512 rows x 1 columns]

In [89]:
df['DepTime'].clip(1000,2000)

0         1157.0
1         1157.0
2         1153.0
3         1150.0
4         1355.0
           ...
637609    1433.0
637610    1224.0
637611    1016.0
637612    1403.0
637613    1754.0
Name: DepTime, Length: 5689512, dtype: float64

Groupby Methods for dataframes of categorical types

In [90]:
df.groupby('Airline')[['DepDelay']].mean()

                                            DepDelay
Airline
Air Wisconsin Airlines Corp                11.405747
Alaska Airlines Inc.                        2.021924
Allegiant Air                              12.922575
American Airlines Inc.                     10.121187
Cape Air                                   -2.729355
Capital Cargo International                10.441951
Comair Inc.                                 9.471686
Commutair Aka Champlain Enterprises, Inc.  24.726451
Compass Airlines                           10.080122
Delta Air Lines Inc.                        5.690527
Empire Airlines Inc.                        8.480185
Endeavor Air Inc.                           9.644629
Envoy Air                                   6.885426
ExpressJet Airlines Inc.                   11.855062
Frontier Airlines Inc.                     19.684102
GoJet Airlines, LLC d/b/a United Express   11.872817
Hawaiian Airlines Inc.                      0.913099
Horizon Air                                 3.073117
JetBlue Airways                            15.869267
Mesa Airlines Inc.                         11.612683
Peninsula Airways Inc.                     10.671280
Republic Airlines                           7.699234
SkyWest Airlines Inc.                       9.949630
Southwest Airlines Co.                     11.138968
Spirit Air Lines                            9.868512
Trans States Airlines                      16.788899
United Air Lines Inc.                      10.060413
Virgin America                              6.333836

In [91]:
df.groupby('Airline')[['DepDelay']].agg(['mean', 'min', 'max'])

                                            DepDelay
                                                mean     min     max
Airline
Air Wisconsin Airlines Corp                11.405747   -49.0  1296.0
Alaska Airlines Inc.                        2.021924  -114.0   839.0
Allegiant Air                              12.922575   -53.0  1462.0
American Airlines Inc.                     10.121187   -31.0  2109.0
Cape Air                                   -2.729355   -50.0   430.0
Capital Cargo International                10.441951   -45.0   841.0
Comair Inc.                                 9.471686   -34.0  1121.0
Commutair Aka Champlain Enterprises, Inc.  24.726451   -31.0  1352.0
Compass Airlines                           10.080122 -1280.0  2625.0
Delta Air Lines Inc.                        5.690527   -40.0  1207.0
Empire Airlines Inc.                        8.480185   -42.0   655.0
Endeavor Air Inc.                           9.644629   -38.0  1921.0
Envoy Air                                   6.885426   -40.0  1163.0
ExpressJet Airlines Inc.                   11.855062   -36.0  1522.0
Frontier Airlines Inc.                     19.684102   -60.0  1254.0
GoJet Airlines, LLC d/b/a United Express   11.872817  -611.0  1545.0
Hawaiian Airlines Inc.                      0.913099   -37.0  2482.0
Horizon Air                                 3.073117   -54.0   640.0
JetBlue Airways                            15.869267   -32.0  1489.0
Mesa Airlines Inc.                         11.612683   -30.0  1789.0
Peninsula Airways Inc.                     10.671280   -33.0   470.0
Republic Airlines                           7.699234   -48.0  1270.0
SkyWest Airlines Inc.                       9.949630   -60.0  2098.0
Southwest Airlines Co.                     11.138968   -49.0   713.0
Spirit Air Lines                            9.868512   -47.0  1527.0
Trans States Airlines                      16.788899   -51.0  1519.0
United Air Lines Inc.                      10.060413  -122.0  1431.0
Virgin America                              6.333836   -24.0   520.0

In [95]:
df.groupby('Airline')[['DepDelay','ArrDelay']].agg(['mean', 'min', 'max'])

                                            DepDelay                  \
                                                mean     min     max
Airline
Air Wisconsin Airlines Corp                11.405747   -49.0  1296.0
Alaska Airlines Inc.                        2.021924  -114.0   839.0
Allegiant Air                              12.922575   -53.0  1462.0
American Airlines Inc.                     10.121187   -31.0  2109.0
Cape Air                                   -2.729355   -50.0   430.0
Capital Cargo International                10.441951   -45.0   841.0
Comair Inc.                                 9.471686   -34.0  1121.0
Commutair Aka Champlain Enterprises, Inc.  24.726451   -31.0  1352.0
Compass Airlines                           10.080122 -1280.0  2625.0
Delta Air Lines Inc.                        5.690527   -40.0  1207.0
Empire Airlines Inc.                        8.480185   -42.0   655.0
Endeavor Air Inc.                           9.644629   -38.0  1921.0
Envoy Air                                   6.885426   -40.0  1163.0
ExpressJet Airlines Inc.                   11.855062   -36.0  1522.0
Frontier Airlines Inc.                     19.684102   -60.0  1254.0
GoJet Airlines, LLC d/b/a United Express   11.872817  -611.0  1545.0
Hawaiian Airlines Inc.                      0.913099   -37.0  2482.0
Horizon Air                                 3.073117   -54.0   640.0
JetBlue Airways                            15.869267   -32.0  1489.0
Mesa Airlines Inc.                         11.612683   -30.0  1789.0
Peninsula Airways Inc.                     10.671280   -33.0   470.0
Republic Airlines                           7.699234   -48.0  1270.0
SkyWest Airlines Inc.                       9.949630   -60.0  2098.0
Southwest Airlines Co.                     11.138968   -49.0   713.0
Spirit Air Lines                            9.868512   -47.0  1527.0
Trans States Airlines                      16.788899   -51.0  1519.0
United Air Lines Inc.                      10.060413  -122.0  1431.0
Virgin America                              6.333836   -24.0   520.0

                                            ArrDelay
                                                mean     min     max
Airline
Air Wisconsin Airlines Corp                 8.013017   -70.0  1292.0
Alaska Airlines Inc.                       -1.180165  -106.0   842.0
Allegiant Air                               9.983518   -98.0  1505.0
American Airlines Inc.                      6.514280   -70.0  2153.0
Cape Air                                   -1.413897   -45.0   446.0
Capital Cargo International                 6.588072   -51.0   814.0
Comair Inc.                                 4.860667   -56.0  1110.0
Commutair Aka Champlain Enterprises, Inc.  21.579446   -60.0  1353.0
Compass Airlines                            6.160631 -1290.0  2635.0
Delta Air Lines Inc.                       -2.225013   -83.0  1206.0
Empire Airlines Inc.                        8.944804   -48.0   654.0
Endeavor Air Inc.                           3.454431   -83.0  1916.0
Envoy Air                                   4.502394   -61.0  1152.0
ExpressJet Airlines Inc.                    8.800352   -63.0  1553.0
Frontier Airlines Inc.                     14.213311   -74.0  1253.0
GoJet Airlines, LLC d/b/a United Express    6.325496  -475.0  1543.0
Hawaiian Airlines Inc.                      0.851310   -67.0  2475.0
Horizon Air                                 1.693461   -73.0   642.0
JetBlue Airways                            11.432516   -79.0  1473.0
Mesa Airlines Inc.                          9.088688   -63.0  1773.0
Peninsula Airways Inc.                      7.485307   -50.0   437.0
Republic Airlines                           3.478926   -77.0  1346.0
SkyWest Airlines Inc.                       6.969415   -91.0  2108.0
Southwest Airlines Co.                      4.519644  -117.0   698.0
Spirit Air Lines                            5.171453   -81.0  1527.0
Trans States Airlines                      13.914852   -53.0  1537.0
United Air Lines Inc.                       5.764875  -120.0  1429.0
Virgin America                              1.727978   -81.0   504.0

In [96]:
df_agg=df.groupby('Airline')[['DepDelay','ArrDelay']].agg(['mean', 'min', 'max'])
df_agg.columns

MultiIndex([('DepDelay', 'mean'),
            ('DepDelay',  'min'),
            ('DepDelay',  'max'),
            ('ArrDelay', 'mean'),
            ('ArrDelay',  'min'),
            ('ArrDelay',  'max')],
           )

In [97]:
df_agg.columns.to_flat_index()

Index([('DepDelay', 'mean'),  ('DepDelay', 'min'),  ('DepDelay', 'max'),
       ('ArrDelay', 'mean'),  ('ArrDelay', 'min'),  ('ArrDelay', 'max')],
      dtype='object')

In [98]:
df_agg.columns=['_'.join(c) for c in df_agg.columns]

In [99]:
df_agg

,DepDelay_mean,DepDelay_min,DepDelay_max,ArrDelay_mean,ArrDelay_min,ArrDelay_max
Airline,,,,,,
Air Wisconsin Airlines Corp,11.405747,-49.0,1296.0,8.013017,-70.0,1292.0
Alaska Airlines Inc.,2.021924,-114.0,839.0,-1.180165,-106.0,842.0
Allegiant Air,12.922575,-53.0,1462.0,9.983518,-98.0,1505.0
American Airlines Inc.,10.121187,-31.0,2109.0,6.514280,-70.0,2153.0
Cape Air,-2.729355,-50.0,430.0,-1.413897,-45.0,446.0
Capital Cargo International,10.441951,-45.0,841.0,6.588072,-51.0,814.0
Comair Inc.,9.471686,-34.0,1121.0,4.860667,-56.0,1110.0
"Commutair Aka Champlain Enterprises, Inc.",24.726451,-31.0,1352.0,21.579446,-60.0,1353.0
Compass Airlines,10.080122,-1280.0,2625.0,6.160631,-1290.0,2635.0
Delta Air Lines Inc.,5.690527,-40.0,1207.0,-2.225013,-83.0,1206.0
Empire Airlines Inc.,8.480185,-42.0,655.0,8.944804,-48.0,654.0
Endeavor Air Inc.,9.644629,-38.0,1921.0,3.454431,-83.0,1916.0
Envoy Air,6.885426,-40.0,1163.0,4.502394,-61.0,1152.0
ExpressJet Airlines Inc.,11.855062,-36.0,1522.0,8.800352,-63.0,1553.0
Frontier Airlines Inc.,19.684102,-60.0,1254.0,14.213311,-74.0,1253.0
"GoJet Airlines, LLC d/b/a United Express",11.872817,-611.0,1545.0,6.325496,-475.0,1543.0
Hawaiian Airlines Inc.,0.913099,-37.0,2482.0,0.851310,-67.0,2475.0
Horizon Air,3.073117,-54.0,640.0,1.693461,-73.0,642.0
JetBlue Airways,15.869267,-32.0,1489.0,11.432516,-79.0,1473.0
Mesa Airlines Inc.,11.612683,-30.0,1789.0,9.088688,-63.0,1773.0
Peninsula Airways Inc.,10.671280,-33.0,470.0,7.485307,-50.0,437.0
Republic Airlines,7.699234,-48.0,1270.0,3.478926,-77.0,1346.0
SkyWest Airlines Inc.,9.949630,-60.0,2098.0,6.969415,-91.0,2108.0
Southwest Airlines Co.,11.138968,-49.0,713.0,4.519644,-117.0,698.0
Spirit Air Lines,9.868512,-47.0,1527.0,5.171453,-81.0,1527.0
Trans States Airlines,16.788899,-51.0,1519.0,13.914852,-53.0,1537.0
United Air Lines Inc.,10.060413,-122.0,1431.0,5.764875,-120.0,1429.0
Virgin America,6.333836,-24.0,520.0,1.727978,-81.0,504.0

New Columns

In [100]:
df.head()

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
0,2018-01-23,Endeavor Air Inc.,ABY,ATL,False,False,1202,1157.0,0.0,-5.0,1256.0,0.0,38.0,62.0,59.0,145.0,2018,1,1,23,2,DL,DL_CODESHARE,19790,DL,3298,9E,20363,9E,N8928A,3298,10146,1014602,30146,"Albany, GA",GA,13,Georgia,34,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,0.0,-1.0,1200-1259,14.0,1211.0,1249.0,7.0,1304,-8.0,0.0,-1.0,1300-1359,1,0.0
1,2018-01-24,Endeavor Air Inc.,ABY,ATL,False,False,1202,1157.0,0.0,-5.0,1258.0,0.0,36.0,62.0,61.0,145.0,2018,1,1,24,3,DL,DL_CODESHARE,19790,DL,3298,9E,20363,9E,N800AY,3298,10146,1014602,30146,"Albany, GA",GA,13,Georgia,34,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,0.0,-1.0,1200-1259,13.0,1210.0,1246.0,12.0,1304,-6.0,0.0,-1.0,1300-1359,1,0.0
2,2018-01-25,Endeavor Air Inc.,ABY,ATL,False,False,1202,1153.0,0.0,-9.0,1302.0,0.0,40.0,62.0,69.0,145.0,2018,1,1,25,4,DL,DL_CODESHARE,19790,DL,3298,9E,20363,9E,N8836A,3298,10146,1014602,30146,"Albany, GA",GA,13,Georgia,34,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,0.0,-1.0,1200-1259,18.0,1211.0,1251.0,11.0,1304,-2.0,0.0,-1.0,1300-1359,1,0.0
3,2018-01-26,Endeavor Air Inc.,ABY,ATL,False,False,1202,1150.0,0.0,-12.0,1253.0,0.0,35.0,62.0,63.0,145.0,2018,1,1,26,5,DL,DL_CODESHARE,19790,DL,3298,9E,20363,9E,N800AY,3298,10146,1014602,30146,"Albany, GA",GA,13,Georgia,34,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,0.0,-1.0,1200-1259,17.0,1207.0,1242.0,11.0,1304,-11.0,0.0,-1.0,1300-1359,1,0.0
4,2018-01-27,Endeavor Air Inc.,ABY,ATL,False,False,1400,1355.0,0.0,-5.0,1459.0,0.0,36.0,60.0,64.0,145.0,2018,1,1,27,6,DL,DL_CODESHARE,19790,DL,3298,9E,20363,9E,N8839E,3298,10146,1014602,30146,"Albany, GA",GA,13,Georgia,34,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,0.0,-1.0,1400-1459,17.0,1412.0,1448.0,11.0,1500,-1.0,0.0,-1.0,1500-1559,1,0.0

In [101]:
df['DepTime2']=df['DepTime']/60

In [102]:
df.head()

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings,DepTime2
0,2018-01-23,Endeavor Air Inc.,ABY,ATL,False,False,1202,1157.0,0.0,-5.0,1256.0,0.0,38.0,62.0,59.0,145.0,2018,1,1,23,2,DL,DL_CODESHARE,19790,DL,3298,9E,20363,9E,N8928A,3298,10146,1014602,30146,"Albany, GA",GA,13,Georgia,34,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,0.0,-1.0,1200-1259,14.0,1211.0,1249.0,7.0,1304,-8.0,0.0,-1.0,1300-1359,1,0.0,19.283333
1,2018-01-24,Endeavor Air Inc.,ABY,ATL,False,False,1202,1157.0,0.0,-5.0,1258.0,0.0,36.0,62.0,61.0,145.0,2018,1,1,24,3,DL,DL_CODESHARE,19790,DL,3298,9E,20363,9E,N800AY,3298,10146,1014602,30146,"Albany, GA",GA,13,Georgia,34,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,0.0,-1.0,1200-1259,13.0,1210.0,1246.0,12.0,1304,-6.0,0.0,-1.0,1300-1359,1,0.0,19.283333
2,2018-01-25,Endeavor Air Inc.,ABY,ATL,False,False,1202,1153.0,0.0,-9.0,1302.0,0.0,40.0,62.0,69.0,145.0,2018,1,1,25,4,DL,DL_CODESHARE,19790,DL,3298,9E,20363,9E,N8836A,3298,10146,1014602,30146,"Albany, GA",GA,13,Georgia,34,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,0.0,-1.0,1200-1259,18.0,1211.0,1251.0,11.0,1304,-2.0,0.0,-1.0,1300-1359,1,0.0,19.216667
3,2018-01-26,Endeavor Air Inc.,ABY,ATL,False,False,1202,1150.0,0.0,-12.0,1253.0,0.0,35.0,62.0,63.0,145.0,2018,1,1,26,5,DL,DL_CODESHARE,19790,DL,3298,9E,20363,9E,N800AY,3298,10146,1014602,30146,"Albany, GA",GA,13,Georgia,34,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,0.0,-1.0,1200-1259,17.0,1207.0,1242.0,11.0,1304,-11.0,0.0,-1.0,1300-1359,1,0.0,19.166667
4,2018-01-27,Endeavor Air Inc.,ABY,ATL,False,False,1400,1355.0,0.0,-5.0,1459.0,0.0,36.0,60.0,64.0,145.0,2018,1,1,27,6,DL,DL_CODESHARE,19790,DL,3298,9E,20363,9E,N8839E,3298,10146,1014602,30146,"Albany, GA",GA,13,Georgia,34,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,0.0,-1.0,1400-1459,17.0,1412.0,1448.0,11.0,1500,-1.0,0.0,-1.0,1500-1559,1,0.0,22.583333

In [103]:
df.assign(DepTime2=df['DepTime']/2)

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings,DepTime2
0,2018-01-23,Endeavor Air Inc.,ABY,ATL,False,False,1202,1157.0,0.0,-5.0,1256.0,0.0,38.0,62.0,59.0,145.0,2018,1,1,23,2,DL,DL_CODESHARE,19790,DL,3298,9E,20363,9E,N8928A,3298,10146,1014602,30146,"Albany, GA",GA,13,Georgia,34,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,0.0,-1.0,1200-1259,14.0,1211.0,1249.0,7.0,1304,-8.0,0.0,-1.0,1300-1359,1,0.0,578.5
1,2018-01-24,Endeavor Air Inc.,ABY,ATL,False,False,1202,1157.0,0.0,-5.0,1258.0,0.0,36.0,62.0,61.0,145.0,2018,1,1,24,3,DL,DL_CODESHARE,19790,DL,3298,9E,20363,9E,N800AY,3298,10146,1014602,30146,"Albany, GA",GA,13,Georgia,34,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,0.0,-1.0,1200-1259,13.0,1210.0,1246.0,12.0,1304,-6.0,0.0,-1.0,1300-1359,1,0.0,578.5
2,2018-01-25,Endeavor Air Inc.,ABY,ATL,False,False,1202,1153.0,0.0,-9.0,1302.0,0.0,40.0,62.0,69.0,145.0,2018,1,1,25,4,DL,DL_CODESHARE,19790,DL,3298,9E,20363,9E,N8836A,3298,10146,1014602,30146,"Albany, GA",GA,13,Georgia,34,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,0.0,-1.0,1200-1259,18.0,1211.0,1251.0,11.0,1304,-2.0,0.0,-1.0,1300-1359,1,0.0,576.5
3,2018-01-26,Endeavor Air Inc.,ABY,ATL,False,False,1202,1150.0,0.0,-12.0,1253.0,0.0,35.0,62.0,63.0,145.0,2018,1,1,26,5,DL,DL_CODESHARE,19790,DL,3298,9E,20363,9E,N800AY,3298,10146,1014602,30146,"Albany, GA",GA,13,Georgia,34,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,0.0,-1.0,1200-1259,17.0,1207.0,1242.0,11.0,1304,-11.0,0.0,-1.0,1300-1359,1,0.0,575.0
4,2018-01-27,Endeavor Air Inc.,ABY,ATL,False,False,1400,1355.0,0.0,-5.0,1459.0,0.0,36.0,60.0,64.0,145.0,2018,1,1,27,6,DL,DL_CODESHARE,19790,DL,3298,9E,20363,9E,N8839E,3298,10146,1014602,30146,"Albany, GA",GA,13,Georgia,34,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,0.0,-1.0,1400-1459,17.0,1412.0,1448.0,11.0,1500,-1.0,0.0,-1.0,1500-1559,1,0.0,677.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
637609,2018-09-11,Air Wisconsin Airlines Corp,SCE,IAD,False,False,1445,1433.0,0.0,-12.0,1515.0,0.0,35.0,61.0,42.0,133.0,2018,3,9,11,2,UA,UA_CODESHARE,19977,UA,3839,ZW,20046,ZW,N437AW,3839,14711,1471105,34711,"State College, PA",PA,42,Pennsylvania,23,12264,1226402,30852,"Washington, DC",VA,51,Virginia,38,0.0,-1.0,1400-1459,4.0,1437.0,1512.0,3.0,1546,-31.0,0.0,-2.0,1500-1559,1,0.0,716.5
637610,2018-09-11,Air Wisconsin Airlines Corp,IAD,GSO,False,False,1235,1224.0,0.0,-11.0,1344.0,0.0,43.0,80.0,80.0,239.0,2018,3,9,11,2,UA,UA_CODESHARE,19977,UA,3838,ZW,20046,ZW,N410AW,3838,12264,1226402,30852,"Washington, DC",VA,51,Virginia,38,11995,1199502,31995,"Greensboro/High Point, NC",NC,37,North Carolina,36,0.0,-1.0,1200-1259,30.0,1254.0,1337.0,7.0,1355,-11.0,0.0,-1.0,1300-1359,1,0.0,612.0
637611,2018-09-11,Air Wisconsin Airlines Corp,EVV,ORD,False,False,1030,1016.0,0.0,-14.0,1137.0,0.0,54.0,94.0,81.0,272.0,2018,3,9,11,2,UA,UA_CODESHARE,19977,UA,3837,ZW,20046,ZW,N467AW,3837,11612,1161206,31612,"Evansville, IN",IN,18,Indiana,42,13930,1393006,30977,"Chicago, IL",IL,17,Illinois,41,0.0,-1.0,1000-1059,20.0,1036.0,1130.0,7.0,1204,-27.0,0.0,-2.0,1200-1259,2,0.0,508.0
637612,2018-09-11,Air Wisconsin Airlines Corp,ORD,HPN,False,False,1410,1403.0,0.0,-7.0,1717.0,0.0,104.0,136.0,134.0,738.0,2018,3,9,11,2,UA,UA_CODESHARE,19977,UA,3837,ZW,20046,ZW,N440AW,3837,13930,1393006,30977,"Chicago, IL",IL,17,Illinois,41,12197,1219702,31703,"White Plains, NY",NY,36,New York,22,0.0,-1.0,1400-1459,25.0,1428.0,1712.0,5.0,1726,-9.0,0.0,-1.0,1700-1759,3,0.0,701.5
637613,2018-09-11,Air Wisconsin Airlines Corp,HPN,ORD,False,False,1800,1754.0,0.0,-6.0,1919.0,0.0,116.0,153.0,145.0,738.0,2018,3,9,11,2,UA,UA_CODESHARE,19977,UA,3836,ZW,20046,ZW,N440AW,3836,12197,1219702,31703,"White Plains, NY",NY,36,New York,22,13930,1393006,30977,"Chicago, IL",IL,17,Illinois,41,0.0,-1.0,1800-1859,14.0,1808.0,1904.0,15.0,1933,-14.0,0.0,-1.0,1900-1959,3,0.0,877.0

#Sorting Data

In [104]:
df.sort_values('ArrDelay')

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings,DepTime2
228175,2018-01-16,Compass Airlines,SEA,PSC,False,False,2240,120.0,0.0,-1280.0,212.0,0.0,-1244.0,62.0,-1228.0,172.0,2018,1,1,16,2,DL,DL_CODESHARE,19790,DL,5747,CP,21167,CP,N622CZ,5747,14747,1474703,30559,"Seattle, WA",WA,53,Washington,93,14252,1425202,34252,"Pasco/Kennewick/Richland, WA",WA,53,Washington,93,0.0,-2.0,2200-2259,12.0,132.0,208.0,4.0,2342,-1290.0,0.0,-2.0,2300-2359,1,0.0,2.000000
226687,2018-01-10,"GoJet Airlines, LLC d/b/a United Express",MSP,STL,False,False,2200,1149.0,0.0,-611.0,1334.0,0.0,65.0,-31.0,105.0,448.0,2018,1,1,10,3,DL,DL_CODESHARE,19790,DL,6191,G7,20500,G7,N658CA,6191,13487,1348702,31650,"Minneapolis, MN",MN,27,Minnesota,63,15016,1501606,31123,"St. Louis, MO",MO,29,Missouri,64,0.0,-2.0,2200-2259,32.0,1221.0,1326.0,8.0,2129,-475.0,0.0,-2.0,2100-2159,2,0.0,19.150000
457467,2018-01-31,Compass Airlines,SEA,SNA,False,False,1248,858.0,0.0,-230.0,1131.0,0.0,128.0,-40.0,153.0,978.0,2018,1,1,31,3,DL,DL_CODESHARE,19790,DL,5773,CP,21167,CP,N630CZ,5773,14747,1474703,30559,"Seattle, WA",WA,53,Washington,93,14908,1490803,32575,"Santa Ana, CA",CA,6,California,91,0.0,-2.0,1200-1259,16.0,914.0,1122.0,9.0,1551,-260.0,0.0,-2.0,1500-1559,4,0.0,14.300000
457514,2018-01-31,"GoJet Airlines, LLC d/b/a United Express",DTW,BHM,False,False,1150,951.0,0.0,-119.0,1036.0,0.0,89.0,-35.0,105.0,625.0,2018,1,1,31,3,DL,DL_CODESHARE,19790,DL,6182,G7,20500,G7,N331CA,6182,11433,1143302,31295,"Detroit, MI",MI,26,Michigan,43,10599,1059904,30599,"Birmingham, AL",AL,1,Alabama,51,0.0,-2.0,1100-1159,13.0,1004.0,1033.0,3.0,1454,-258.0,0.0,-2.0,1400-1459,3,0.0,15.850000
457432,2018-01-31,Compass Airlines,SEA,SAN,False,False,1500,1129.0,0.0,-211.0,1355.0,0.0,122.0,-36.0,146.0,1050.0,2018,1,1,31,3,DL,DL_CODESHARE,19790,DL,5738,CP,21167,CP,N602CZ,5738,14747,1474703,30559,"Seattle, WA",WA,53,Washington,93,14679,1467903,33570,"San Diego, CA",CA,6,California,91,0.0,-2.0,1500-1559,14.0,1143.0,1345.0,10.0,1809,-254.0,0.0,-2.0,1800-1859,5,0.0,18.816667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
636866,2018-09-12,Air Wisconsin Airlines Corp,ORD,ROA,False,True,745,737.0,0.0,-8.0,1304.0,NaN,NaN,113.0,NaN,531.0,2018,3,9,12,3,UA,UA_CODESHARE,19977,UA,3907,ZW,20046,ZW,N426AW,3907,13930,1393006,30977,"Chicago, IL",IL,17,Illinois,41,14574,1457405,34574,"Roanoke, VA",VA,51,Virginia,38,0.0,-1.0,0700-0759,21.0,758.0,1300.0,4.0,1038,NaN,NaN,NaN,1000-1059,3,1.0,12.283333
636888,2018-09-12,Air Wisconsin Airlines Corp,IAD,FAY,True,False,1735,NaN,NaN,NaN,NaN,NaN,NaN,83.0,NaN,284.0,2018,3,9,12,3,UA,UA_CODESHARE,19977,UA,3881,ZW,20046,ZW,None,3881,12264,1226402,30852,"Washington, DC",VA,51,Virginia,38,11641,1164102,31641,"Fayetteville, NC",NC,37,North Carolina,36,NaN,NaN,1700-1759,NaN,NaN,NaN,NaN,1858,NaN,NaN,NaN,1800-1859,2,0.0,NaN
636894,2018-09-12,Air Wisconsin Airlines Corp,ORD,ILM,True,False,1800,NaN,NaN,NaN,NaN,NaN,NaN,136.0,NaN,760.0,2018,3,9,12,3,UA,UA_CODESHARE,19977,UA,3874,ZW,20046,ZW,None,3874,13930,1393006,30977,"Chicago, IL",IL,17,Illinois,41,12323,1232305,32323,"Wilmington, NC",NC,37,North Carolina,36,NaN,NaN,1800-1859,NaN,NaN,NaN,NaN,2116,NaN,NaN,NaN,2100-2159,4,0.0,NaN
637033,2018-09-11,"Commutair Aka Champlain Enterprises, Inc.",IND,EWR,False,True,1200,1355.0,115.0,115.0,1833.0,NaN,NaN,127.0,NaN,645.0,2018,3,9,11,2,UA,UA_CODESHARE,19977,UA,4979,C5,20445,C5,N11193,4979,12339,1233904,32337,"Indianapolis, IN",IN,18,Indiana,42,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,1.0,7.0,1200-1259,11.0,1406.0,1822.0,11.0,1407,NaN,NaN,NaN,1400-1459,3,1.0,22.583333
637122,2018-09-11,"Commutair Aka Champlain Enterprises, Inc.",EWR,PQI,False,True,935,927.0,0.0,-8.0,1552.0,NaN,NaN,125.0,NaN,515.0,2018,3,9,11,2,UA,UA_CODESHARE,19977,UA,4904,C5,20445,C5,N13161,4904,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,14231,1423102,34231,"Presque Isle/Houlton, ME",ME,23,Maine,12,0.0,-1.0,0900-0959,62.0,1029.0,1550.0,2.0,1140,NaN,NaN,NaN,1100-1159,3,1.0,15.450000

In [105]:
df[['FlightDate','Airline','ArrDelay']].sort_values('ArrDelay', ascending=False)

       FlightDate                                    Airline  ArrDelay
616002 2018-09-16                           Compass Airlines    2635.0
219748 2018-02-09                     Hawaiian Airlines Inc.    2475.0
219756 2018-02-09                     Hawaiian Airlines Inc.    2454.0
530308 2018-10-21                     American Airlines Inc.    2153.0
5443   2018-12-09                      SkyWest Airlines Inc.    2108.0
...           ...                                        ...       ...
636866 2018-09-12                Air Wisconsin Airlines Corp       NaN
636888 2018-09-12                Air Wisconsin Airlines Corp       NaN
636894 2018-09-12                Air Wisconsin Airlines Corp       NaN
637033 2018-09-11  Commutair Aka Champlain Enterprises, Inc.       NaN
637122 2018-09-11  Commutair Aka Champlain Enterprises, Inc.       NaN

[5689512 rows x 3 columns]

In [106]:
df[['FlightDate','Airline','ArrDelay']].sort_values('ArrDelay', ascending=False).reset_index(drop=True)

        FlightDate                                    Airline  ArrDelay
0       2018-09-16                           Compass Airlines    2635.0
1       2018-02-09                     Hawaiian Airlines Inc.    2475.0
2       2018-02-09                     Hawaiian Airlines Inc.    2454.0
3       2018-10-21                     American Airlines Inc.    2153.0
4       2018-12-09                      SkyWest Airlines Inc.    2108.0
...            ...                                        ...       ...
5689507 2018-09-12                Air Wisconsin Airlines Corp       NaN
5689508 2018-09-12                Air Wisconsin Airlines Corp       NaN
5689509 2018-09-12                Air Wisconsin Airlines Corp       NaN
5689510 2018-09-11  Commutair Aka Champlain Enterprises, Inc.       NaN
5689511 2018-09-11  Commutair Aka Champlain Enterprises, Inc.       NaN

[5689512 rows x 3 columns]

In [107]:
df[['FlightDate','Airline','ArrDelay']].sort_index()

       FlightDate                      Airline  ArrDelay
0      2018-01-23            Endeavor Air Inc.      -8.0
0      2018-12-18        SkyWest Airlines Inc.     -28.0
0      2018-02-04              JetBlue Airways      -5.0
0      2018-03-28        United Air Lines Inc.      -4.0
0      2018-04-28              JetBlue Airways       NaN
...           ...                          ...       ...
670085 2018-10-14  Capital Cargo International     -17.0
670086 2018-10-15  Capital Cargo International      49.0
670087 2018-10-16  Capital Cargo International     -16.0
670088 2018-10-17  Capital Cargo International     -11.0
670089 2018-10-18  Capital Cargo International     -13.0

[5689512 rows x 3 columns]

In [108]:
df[['FlightDate','Airline','ArrDelay']]

       FlightDate                      Airline  ArrDelay
0      2018-01-23            Endeavor Air Inc.      -8.0
1      2018-01-24            Endeavor Air Inc.      -6.0
2      2018-01-25            Endeavor Air Inc.      -2.0
3      2018-01-26            Endeavor Air Inc.     -11.0
4      2018-01-27            Endeavor Air Inc.      -1.0
...           ...                          ...       ...
637609 2018-09-11  Air Wisconsin Airlines Corp     -31.0
637610 2018-09-11  Air Wisconsin Airlines Corp     -11.0
637611 2018-09-11  Air Wisconsin Airlines Corp     -27.0
637612 2018-09-11  Air Wisconsin Airlines Corp      -9.0
637613 2018-09-11  Air Wisconsin Airlines Corp     -14.0

[5689512 rows x 3 columns]

In [110]:
df[['FlightDate','Airline','ArrDelay']].isna().sum()

FlightDate         0
Airline            0
ArrDelay      102893
dtype: int64

In [114]:
df[['FlightDate','Airline','ArrDelay']].dropna(subset=['ArrDelay'])

       FlightDate                      Airline  ArrDelay
0      2018-01-23            Endeavor Air Inc.      -8.0
1      2018-01-24            Endeavor Air Inc.      -6.0
2      2018-01-25            Endeavor Air Inc.      -2.0
3      2018-01-26            Endeavor Air Inc.     -11.0
4      2018-01-27            Endeavor Air Inc.      -1.0
...           ...                          ...       ...
637609 2018-09-11  Air Wisconsin Airlines Corp     -31.0
637610 2018-09-11  Air Wisconsin Airlines Corp     -11.0
637611 2018-09-11  Air Wisconsin Airlines Corp     -27.0
637612 2018-09-11  Air Wisconsin Airlines Corp      -9.0
637613 2018-09-11  Air Wisconsin Airlines Corp     -14.0

[5586619 rows x 3 columns]

In [115]:
df[['FlightDate','Airline','ArrDelay']].isna().sum()

FlightDate         0
Airline            0
ArrDelay      102893
dtype: int64

In [116]:
df[['FlightDate','Airline','ArrDelay']].fillna(-999)

       FlightDate                      Airline  ArrDelay
0      2018-01-23            Endeavor Air Inc.      -8.0
1      2018-01-24            Endeavor Air Inc.      -6.0
2      2018-01-25            Endeavor Air Inc.      -2.0
3      2018-01-26            Endeavor Air Inc.     -11.0
4      2018-01-27            Endeavor Air Inc.      -1.0
...           ...                          ...       ...
637609 2018-09-11  Air Wisconsin Airlines Corp     -31.0
637610 2018-09-11  Air Wisconsin Airlines Corp     -11.0
637611 2018-09-11  Air Wisconsin Airlines Corp     -27.0
637612 2018-09-11  Air Wisconsin Airlines Corp      -9.0
637613 2018-09-11  Air Wisconsin Airlines Corp     -14.0

[5689512 rows x 3 columns]

In [117]:
df['ArrDelay'].fillna(df['ArrDelay'].mean())

0         -8.0
1         -6.0
2         -2.0
3        -11.0
4         -1.0
          ...
637609   -31.0
637610   -11.0
637611   -27.0
637612    -9.0
637613   -14.0
Name: ArrDelay, Length: 5689512, dtype: float64

In [118]:
df['ArrDelay'].isna().sum()

102893

Combining Data

In [119]:
df['Airline'].value_counts()

Airline
Southwest Airlines Co.                       1352552
United Air Lines Inc.                         621565
SkyWest Airlines Inc.                         531792
Delta Air Lines Inc.                          461718
American Airlines Inc.                        385183
JetBlue Airways                               305010
Republic Airlines                             203529
Alaska Airlines Inc.                          184751
Spirit Air Lines                              176178
ExpressJet Airlines Inc.                      167180
Mesa Airlines Inc.                            153697
Envoy Air                                     127750
Frontier Airlines Inc.                        120035
Endeavor Air Inc.                             120030
Comair Inc.                                   117132
Air Wisconsin Airlines Corp                    98763
Allegiant Air                                  96221
Horizon Air                                    85245
Hawaiian Airlines Inc.                         83723
Trans States Airlines                          66885
GoJet Airlines, LLC d/b/a United Express       63498
Commutair Aka Champlain Enterprises, Inc.      48010
Compass Airlines                               44898
Capital Cargo International                    44440
Virgin America                                 17670
Empire Airlines Inc.                            9087
Cape Air                                        1661
Peninsula Airways Inc.                          1309
Name: count, dtype: int64

In [123]:
df1=df.query('Airline=="Southwest Airlines Co."').copy()
df2=df.query('Airline=="Delta Air Lines Inc."').copy()

In [125]:
pd.concat([df1,df2])

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings,DepTime2
55989,2018-01-09,Southwest Airlines Co.,LAS,MSY,True,False,1840,NaN,NaN,NaN,NaN,NaN,NaN,195.0,NaN,1500.0,2018,1,1,9,2,WN,WN,19393,WN,5739,WN,19393,WN,N8532S,5739,12889,1288903,32211,"Las Vegas, NV",NV,32,Nevada,85,13495,1349505,33495,"New Orleans, LA",LA,22,Louisiana,72,NaN,NaN,1800-1859,NaN,NaN,NaN,NaN,2355,NaN,NaN,NaN,2300-2359,7,0.0,NaN
55990,2018-01-09,Southwest Airlines Co.,LAS,OAK,False,False,925,1029.0,64.0,64.0,1154.0,54.0,64.0,95.0,85.0,407.0,2018,1,1,9,2,WN,WN,19393,WN,103,WN,19393,WN,N482WN,103,12889,1288903,32211,"Las Vegas, NV",NV,32,Nevada,85,13796,1379608,32457,"Oakland, CA",CA,6,California,91,1.0,4.0,0900-0959,16.0,1045.0,1149.0,5.0,1100,54.0,1.0,3.0,1100-1159,2,0.0,17.150000
55991,2018-01-09,Southwest Airlines Co.,LAS,OAK,False,False,1820,1826.0,6.0,6.0,1949.0,0.0,67.0,95.0,83.0,407.0,2018,1,1,9,2,WN,WN,19393,WN,232,WN,19393,WN,N8647A,232,12889,1288903,32211,"Las Vegas, NV",NV,32,Nevada,85,13796,1379608,32457,"Oakland, CA",CA,6,California,91,0.0,0.0,1800-1859,12.0,1838.0,1945.0,4.0,1955,-6.0,0.0,-1.0,1900-1959,2,0.0,30.433333
55992,2018-01-09,Southwest Airlines Co.,LAS,OAK,True,False,2055,NaN,NaN,NaN,NaN,NaN,NaN,90.0,NaN,407.0,2018,1,1,9,2,WN,WN,19393,WN,924,WN,19393,WN,N7826B,924,12889,1288903,32211,"Las Vegas, NV",NV,32,Nevada,85,13796,1379608,32457,"Oakland, CA",CA,6,California,91,NaN,NaN,2000-2059,NaN,NaN,NaN,NaN,2225,NaN,NaN,NaN,2200-2259,2,0.0,NaN
55993,2018-01-09,Southwest Airlines Co.,LAS,OAK,False,False,2155,2317.0,82.0,82.0,41.0,76.0,71.0,90.0,84.0,407.0,2018,1,1,9,2,WN,WN,19393,WN,1108,WN,19393,WN,N8323C,1108,12889,1288903,32211,"Las Vegas, NV",NV,32,Nevada,85,13796,1379608,32457,"Oakland, CA",CA,6,California,91,1.0,5.0,2100-2159,8.0,2325.0,36.0,5.0,2325,76.0,1.0,5.0,2300-2359,2,0.0,38.616667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
615510,2018-09-10,Delta Air Lines Inc.,ATL,LAX,False,False,2130,2140.0,10.0,10.0,2302.0,0.0,237.0,282.0,262.0,1947.0,2018,3,9,10,1,DL,DL,19790,DL,1128,DL,19790,DL,N840DN,1128,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,12892,1289208,32575,"Los Angeles, CA",CA,6,California,91,0.0,0.0,2100-2159,18.0,2158.0,2255.0,7.0,2312,-10.0,0.0,-1.0,2300-2359,8,0.0,35.666667
615511,2018-09-10,Delta Air Lines Inc.,ATL,HPN,False,False,943,944.0,1.0,1.0,1210.0,11.0,122.0,136.0,146.0,780.0,2018,3,9,10,1,DL,DL,19790,DL,1129,DL,19790,DL,N932AT,1129,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,12197,1219702,31703,"White Plains, NY",NY,36,New York,22,0.0,0.0,0900-0959,20.0,1004.0,1206.0,4.0,1159,11.0,0.0,0.0,1100-1159,4,0.0,15.733333
615512,2018-09-10,Delta Air Lines Inc.,HPN,ATL,False,False,1235,1300.0,25.0,25.0,1506.0,6.0,107.0,145.0,126.0,780.0,2018,3,9,10,1,DL,DL,19790,DL,1129,DL,19790,DL,N932AT,1129,12197,1219702,31703,"White Plains, NY",NY,36,New York,22,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,1.0,1.0,1200-1259,13.0,1313.0,1500.0,6.0,1500,6.0,0.0,0.0,1500-1559,4,0.0,21.666667
615513,2018-09-10,Delta Air Lines Inc.,ATL,MSP,False,False,2220,2218.0,0.0,-2.0,2345.0,0.0,130.0,154.0,147.0,907.0,2018,3,9,10,1,DL,DL,19790,DL,1130,DL,19790,DL,N330DX,1130,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,13487,1348702,31650,"Minneapolis, MN",MN,27,Minnesota,63,0.0,-1.0,2200-2259,13.0,2231.0,2341.0,4.0,2354,-9.0,0.0,-1.0,2300-2359,4,0.0,36.966667
615514,2018-09-10,Delta Air Lines Inc.,LGA,FLL,False,False,1537,1652.0,75.0,75.0,1943.0,48.0,144.0,198.0,171.0,1076.0,2018,3,9,10,1,DL,DL,19790,DL,1131,DL,19790,DL,N322NB,1131,12953,1295304,31703,"New York, NY",NY,36,New York,22,11697,1169706,32467,"Fort Lauderdale, FL",FL,12,Florida,33,1.0,5.0,1500-1559,24.0,1716.0,1940.0,3.0,1855,48.0,1.0,3.0,1800-1859,5,0.0,27.533333

In [126]:
df_stack=pd.concat([df1,df2])

In [128]:
df1=df1.reset_index(drop=True)
df2=df2.reset_index(drop=True)

In [129]:
pd.concat([df1,df2], axis=1)

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings,DepTime2,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings,DepTime2
0,2018-01-09,Southwest Airlines Co.,LAS,MSY,True,False,1840,NaN,NaN,NaN,NaN,NaN,NaN,195.0,NaN,1500.0,2018,1,1,9,2,WN,WN,19393,WN,5739,WN,19393,WN,N8532S,5739,12889,1288903,32211,"Las Vegas, NV",NV,32,Nevada,85,13495,1349505,33495,"New Orleans, LA",LA,22,Louisiana,72,NaN,NaN,1800-1859,NaN,NaN,NaN,NaN,2355,NaN,NaN,NaN,2300-2359,7,0.0,NaN,2018-01-27,Delta Air Lines Inc.,ATL,ORF,False,False,1608.0,1606.0,0.0,-2.0,1730.0,0.0,73.0,95.0,84.0,516.0,2018.0,1.0,1.0,27.0,6.0,DL,DL,19790.0,DL,1378.0,DL,19790.0,DL,N923DL,1378.0,10397.0,1039707.0,30397.0,"Atlanta, GA",GA,13.0,Georgia,34.0,13931.0,1393102.0,33667.0,"Norfolk, VA",VA,51.0,Virginia,38.0,0.0,-1.0,1600-1659,8.0,1614.0,1727.0,3.0,1743.0,-13.0,0.0,-1.0,1700-1759,3.0,0.0,26.766667
1,2018-01-09,Southwest Airlines Co.,LAS,OAK,False,False,925,1029.0,64.0,64.0,1154.0,54.0,64.0,95.0,85.0,407.0,2018,1,1,9,2,WN,WN,19393,WN,103,WN,19393,WN,N482WN,103,12889,1288903,32211,"Las Vegas, NV",NV,32,Nevada,85,13796,1379608,32457,"Oakland, CA",CA,6,California,91,1.0,4.0,0900-0959,16.0,1045.0,1149.0,5.0,1100,54.0,1.0,3.0,1100-1159,2,0.0,17.150000,2018-01-27,Delta Air Lines Inc.,ATL,GSO,False,False,1700.0,1656.0,0.0,-4.0,1757.0,0.0,48.0,75.0,61.0,306.0,2018.0,1.0,1.0,27.0,6.0,DL,DL,19790.0,DL,1380.0,DL,19790.0,DL,N912DE,1380.0,10397.0,1039707.0,30397.0,"Atlanta, GA",GA,13.0,Georgia,34.0,11995.0,1199502.0,31995.0,"Greensboro/High Point, NC",NC,37.0,North Carolina,36.0,0.0,-1.0,1700-1759,10.0,1706.0,1754.0,3.0,1815.0,-18.0,0.0,-2.0,1800-1859,2.0,0.0,27.600000
2,2018-01-09,Southwest Airlines Co.,LAS,OAK,False,False,1820,1826.0,6.0,6.0,1949.0,0.0,67.0,95.0,83.0,407.0,2018,1,1,9,2,WN,WN,19393,WN,232,WN,19393,WN,N8647A,232,12889,1288903,32211,"Las Vegas, NV",NV,32,Nevada,85,13796,1379608,32457,"Oakland, CA",CA,6,California,91,0.0,0.0,1800-1859,12.0,1838.0,1945.0,4.0,1955,-6.0,0.0,-1.0,1900-1959,2,0.0,30.433333,2018-01-27,Delta Air Lines Inc.,TPA,MSP,False,False,720.0,716.0,0.0,-4.0,928.0,0.0,173.0,207.0,192.0,1306.0,2018.0,1.0,1.0,27.0,6.0,DL,DL,19790.0,DL,1381.0,DL,19790.0,DL,N699DL,1381.0,15304.0,1530402.0,33195.0,"Tampa, FL",FL,12.0,Florida,33.0,13487.0,1348702.0,31650.0,"Minneapolis, MN",MN,27.0,Minnesota,63.0,0.0,-1.0,0700-0759,15.0,731.0,924.0,4.0,947.0,-19.0,0.0,-2.0,0900-0959,6.0,0.0,11.933333
3,2018-01-09,Southwest Airlines Co.,LAS,OAK,True,False,2055,NaN,NaN,NaN,NaN,NaN,NaN,90.0,NaN,407.0,2018,1,1,9,2,WN,WN,19393,WN,924,WN,19393,WN,N7826B,924,12889,1288903,32211,"Las Vegas, NV",NV,32,Nevada,85,13796,1379608,32457,"Oakland, CA",CA,6,California,91,NaN,NaN,2000-2059,NaN,NaN,NaN,NaN,2225,NaN,NaN,NaN,2200-2259,2,0.0,NaN,2018-01-27,Delta Air Lines Inc.,LIH,LAX,False,False,2225.0,2219.0,0.0,-6.0,551.0,7.0,311.0,319.0,332.0,2615.0,2018.0,1.0,1.0,27.0,6.0,DL,DL,19790.0,DL,1382.0,DL,19790.0,DL,N544US,1382.0,12982.0,1298202.0,32982.0,"Lihue, HI",HI,15.0,Hawaii,2.0,12892.0,1289208.0,32575.0,"Los Angeles, CA",CA,6.0,California,91.0,0.0,-1.0,2200-2259,17.0,2236.0,547.0,4.0,544.0,7.0,0.0,0.0,0001-0559,11.0,0.0,36.983333
4,2018-01-09,Southwest Airlines Co.,LAS,OAK,False,False,2155,2317.0,82.0,82.0,41.0,76.0,71.0,90.0,84.0,407.0,2018,1,1,9,2,WN,WN,19393,WN,1108,WN,19393,WN,N8323C,1108,12889,1288903,32211,"Las Vegas, NV",NV,32,Nevada,85,13796,1379608,32457,"Oakland, CA",CA,6,California,91,1.0,5.0,2100-2159,8.0,2325.0,36.0,5.0,2325,76.0,1.0,5.0,2300-2359,2,0.0,38.616667,2018-01-27,Delta Air Lines Inc.,SMF,SLC,False,False,600.0,553.0,0.0,-7.0,824.0,0.0,73.0,103.0,91.0,532.0,2018.0,1.0,1.0,27.0,6.0,DL,DL,19790.0,DL,1384.0,DL,19790.0,DL,N3766,1384.0,14893.0,1489302.0,33192.0,"Sacramento, CA",CA,6.0,California,91.0,14869.0,1486903.0,34614.0,"Salt Lake City, UT",UT,49.0,Utah,87.0,0.0,-1.0,0600-0659,12.0,605.0,818.0,6.0,843.0,-19.0,0.0,-2.0,0800-0859,3.0,0.0,9.216667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1352547,2018-09-21,Southwest Airlines Co.,HOU,DAL,False,False,1530,1602.0,32.0,32.0,1757.0,82.0,65.0,65.0,115.0,239.0,2018,3,9,21,5,WN,WN,19393,WN,38,WN,19393,WN,N8677A,38,12191,1219102,31453,"Houston, TX",TX,48,Texas,74,11259,1125903,30194,"Dallas, TX",TX,48,Texas,74,1.0,2.0,1500-1559,45.0,1647.0,1752.0,5.0,1635,82.0,1.0,5.0,1600-1659,1,0.0,26.700000,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1352548,2018-09-21,Southwest Airlines Co.,HOU,DAL,False,True,1600,2148.0,348.0,348.0,NaN,NaN,NaN,65.0,NaN,239.0,2018,3,9,21,5,WN,WN,19393,WN,40,WN,19393,WN,N755SA,40,12191,1219102,31453,"Houston, TX",TX,48,Texas,74,11259,1125903,30194,"Dallas, TX",TX,48,Texas,74,1.0,12.0,1600-1659,6.0,2154.0,NaN,NaN,1705,NaN,NaN,NaN,1700-1759,1,1.0,35.800000,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1352549,2018-09-21,Southwest Airlines Co.,HOU,DAL,False,True,1630,2043.0,253.0,253.0,NaN,NaN,NaN,70.0,NaN,239.0,2018,3,9,21,5,WN,WN,19393,WN,42,WN,19393,WN,N7855A,42,12191,1219102,31453,"Houston, TX",TX,48,Texas,74,11259,1125903,30194,"Dallas, TX",TX,48,Texas,74,1.0,12.0,1600-1659,5.0,2048.0,NaN,NaN,1740,NaN,NaN,NaN,1700-1759,1,1.0,34.050000,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1352550,2018-09-21,Southwest Airlines Co.,HOU,DAL,True,False,1700,NaN,NaN,NaN,NaN,NaN,NaN,60.0,NaN,239.0,2018,3,9,21,5,WN,WN,19393,WN,44,WN,19393,WN,N8570W,44,12191,1219102,31453,"Houston, TX",TX,48,Texas,74,11259,1125903,30194,"Dallas, TX",TX,48,Texas,74,NaN,NaN,1700-1759,NaN,NaN,NaN,NaN,1800,NaN,NaN,NaN,1800-1859,1,0.0,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1352551,2018-09-21,Southwest Airlines Co.,HOU,DAL,False,True,1830,2024.0,114.0,114.0,NaN,NaN,NaN,60.0,NaN,239.0,2018,3,9,21,5,WN,WN,19393,WN,50,WN,19393,WN,N8692F,50,12191,1219102,31453,"Houston, TX",TX,48,Texas,74,11259,1125903,30194,"Dallas, TX",TX,48,Texas,74,1.0,7.0,1800-1859,8.0,2032.0,NaN,NaN,1930,NaN,NaN,NaN,1900-1959,1,1.0,33.733333,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [130]:
df_side=pd.concat([df1,df2], axis=1)

In [131]:
df1.shape, df2.shape, df_stack.shape, df_side.shape

((1352552, 62), (461718, 62), (1814270, 62), (1352552, 124))

Better to Merge Data instead of concatenating by columns or axis=1 because there are now multiple columns with same names

In [133]:
df1=df.groupby(['Airline', 'FlightDate'])[['DepDelay']].mean().reset_index()
df2=df.groupby(['Airline', 'FlightDate'])[['ArrDelay']].mean().reset_index()

In [134]:
df1.merge(df2)

                          Airline FlightDate   DepDelay   ArrDelay
0     Air Wisconsin Airlines Corp 2018-01-01  59.928994  55.869822
1     Air Wisconsin Airlines Corp 2018-01-02  56.071429  52.307692
2     Air Wisconsin Airlines Corp 2018-01-03  68.344633  69.738636
3     Air Wisconsin Airlines Corp 2018-01-04  15.948387  13.366013
4     Air Wisconsin Airlines Corp 2018-01-05  30.919753  27.223602
...                           ...        ...        ...        ...
8093               Virgin America 2018-03-27   2.608108  -3.554054
8094               Virgin America 2018-03-28   6.461883  -0.179372
8095               Virgin America 2018-03-29   3.982222  -0.524444
8096               Virgin America 2018-03-30  16.986425  10.285068
8097               Virgin America 2018-03-31   3.298429  -4.915344

[8098 rows x 4 columns]

In [135]:
df1.merge(df2, how='left')

                          Airline FlightDate   DepDelay   ArrDelay
0     Air Wisconsin Airlines Corp 2018-01-01  59.928994  55.869822
1     Air Wisconsin Airlines Corp 2018-01-02  56.071429  52.307692
2     Air Wisconsin Airlines Corp 2018-01-03  68.344633  69.738636
3     Air Wisconsin Airlines Corp 2018-01-04  15.948387  13.366013
4     Air Wisconsin Airlines Corp 2018-01-05  30.919753  27.223602
...                           ...        ...        ...        ...
8093               Virgin America 2018-03-27   2.608108  -3.554054
8094               Virgin America 2018-03-28   6.461883  -0.179372
8095               Virgin America 2018-03-29   3.982222  -0.524444
8096               Virgin America 2018-03-30  16.986425  10.285068
8097               Virgin America 2018-03-31   3.298429  -4.915344

[8098 rows x 4 columns]

In [136]:
df1.merge(df2, how='outer')

                          Airline FlightDate   DepDelay   ArrDelay
0     Air Wisconsin Airlines Corp 2018-01-01  59.928994  55.869822
1     Air Wisconsin Airlines Corp 2018-01-02  56.071429  52.307692
2     Air Wisconsin Airlines Corp 2018-01-03  68.344633  69.738636
3     Air Wisconsin Airlines Corp 2018-01-04  15.948387  13.366013
4     Air Wisconsin Airlines Corp 2018-01-05  30.919753  27.223602
...                           ...        ...        ...        ...
8093               Virgin America 2018-03-27   2.608108  -3.554054
8094               Virgin America 2018-03-28   6.461883  -0.179372
8095               Virgin America 2018-03-29   3.982222  -0.524444
8096               Virgin America 2018-03-30  16.986425  10.285068
8097               Virgin America 2018-03-31   3.298429  -4.915344

[8098 rows x 4 columns]

In [137]:
pd.merge(df1,df2, on=['Airline', 'FlightDate'])

                          Airline FlightDate   DepDelay   ArrDelay
0     Air Wisconsin Airlines Corp 2018-01-01  59.928994  55.869822
1     Air Wisconsin Airlines Corp 2018-01-02  56.071429  52.307692
2     Air Wisconsin Airlines Corp 2018-01-03  68.344633  69.738636
3     Air Wisconsin Airlines Corp 2018-01-04  15.948387  13.366013
4     Air Wisconsin Airlines Corp 2018-01-05  30.919753  27.223602
...                           ...        ...        ...        ...
8093               Virgin America 2018-03-27   2.608108  -3.554054
8094               Virgin America 2018-03-28   6.461883  -0.179372
8095               Virgin America 2018-03-29   3.982222  -0.524444
8096               Virgin America 2018-03-30  16.986425  10.285068
8097               Virgin America 2018-03-31   3.298429  -4.915344

[8098 rows x 4 columns]

In [138]:
pd.merge(df1, df2, on=['Airline'], suffixes=('_dep','_arr'))

,Airline,FlightDate_dep,DepDelay,FlightDate_arr,ArrDelay
0,Air Wisconsin Airlines Corp,2018-01-01,59.928994,2018-01-01,55.869822
1,Air Wisconsin Airlines Corp,2018-01-01,59.928994,2018-01-02,52.307692
2,Air Wisconsin Airlines Corp,2018-01-01,59.928994,2018-01-03,69.738636
3,Air Wisconsin Airlines Corp,2018-01-01,59.928994,2018-01-04,13.366013
4,Air Wisconsin Airlines Corp,2018-01-01,59.928994,2018-01-05,27.223602
...,...,...,...,...,...
2595787,Virgin America,2018-03-31,3.298429,2018-03-27,-3.554054
2595788,Virgin America,2018-03-31,3.298429,2018-03-28,-0.179372
2595789,Virgin America,2018-03-31,3.298429,2018-03-29,-0.524444
2595790,Virgin America,2018-03-31,3.298429,2018-03-30,10.285068
2595791,Virgin America,2018-03-31,3.298429,2018-03-31,-4.915344

In [139]:
pd.merge(df1, df2, left_on=['Airline'], right_on=['Airline'])

,Airline,FlightDate_x,DepDelay,FlightDate_y,ArrDelay
0,Air Wisconsin Airlines Corp,2018-01-01,59.928994,2018-01-01,55.869822
1,Air Wisconsin Airlines Corp,2018-01-01,59.928994,2018-01-02,52.307692
2,Air Wisconsin Airlines Corp,2018-01-01,59.928994,2018-01-03,69.738636
3,Air Wisconsin Airlines Corp,2018-01-01,59.928994,2018-01-04,13.366013
4,Air Wisconsin Airlines Corp,2018-01-01,59.928994,2018-01-05,27.223602
...,...,...,...,...,...
2595787,Virgin America,2018-03-31,3.298429,2018-03-27,-3.554054
2595788,Virgin America,2018-03-31,3.298429,2018-03-28,-0.179372
2595789,Virgin America,2018-03-31,3.298429,2018-03-29,-0.524444
2595790,Virgin America,2018-03-31,3.298429,2018-03-30,10.285068
2595791,Virgin America,2018-03-31,3.298429,2018-03-31,-4.915344

In [141]:
pd.merge(df1, df2, left_on=['Airline'], right_on=['Airline'], suffixes=('_dep','_arr'))

,Airline,FlightDate_dep,DepDelay,FlightDate_arr,ArrDelay
0,Air Wisconsin Airlines Corp,2018-01-01,59.928994,2018-01-01,55.869822
1,Air Wisconsin Airlines Corp,2018-01-01,59.928994,2018-01-02,52.307692
2,Air Wisconsin Airlines Corp,2018-01-01,59.928994,2018-01-03,69.738636
3,Air Wisconsin Airlines Corp,2018-01-01,59.928994,2018-01-04,13.366013
4,Air Wisconsin Airlines Corp,2018-01-01,59.928994,2018-01-05,27.223602
...,...,...,...,...,...
2595787,Virgin America,2018-03-31,3.298429,2018-03-27,-3.554054
2595788,Virgin America,2018-03-31,3.298429,2018-03-28,-0.179372
2595789,Virgin America,2018-03-31,3.298429,2018-03-29,-0.524444
2595790,Virgin America,2018-03-31,3.298429,2018-03-30,10.285068
2595791,Virgin America,2018-03-31,3.298429,2018-03-31,-4.915344

In [142]:
df.head()

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings,DepTime2
0,2018-01-23,Endeavor Air Inc.,ABY,ATL,False,False,1202,1157.0,0.0,-5.0,1256.0,0.0,38.0,62.0,59.0,145.0,2018,1,1,23,2,DL,DL_CODESHARE,19790,DL,3298,9E,20363,9E,N8928A,3298,10146,1014602,30146,"Albany, GA",GA,13,Georgia,34,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,0.0,-1.0,1200-1259,14.0,1211.0,1249.0,7.0,1304,-8.0,0.0,-1.0,1300-1359,1,0.0,19.283333
1,2018-01-24,Endeavor Air Inc.,ABY,ATL,False,False,1202,1157.0,0.0,-5.0,1258.0,0.0,36.0,62.0,61.0,145.0,2018,1,1,24,3,DL,DL_CODESHARE,19790,DL,3298,9E,20363,9E,N800AY,3298,10146,1014602,30146,"Albany, GA",GA,13,Georgia,34,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,0.0,-1.0,1200-1259,13.0,1210.0,1246.0,12.0,1304,-6.0,0.0,-1.0,1300-1359,1,0.0,19.283333
2,2018-01-25,Endeavor Air Inc.,ABY,ATL,False,False,1202,1153.0,0.0,-9.0,1302.0,0.0,40.0,62.0,69.0,145.0,2018,1,1,25,4,DL,DL_CODESHARE,19790,DL,3298,9E,20363,9E,N8836A,3298,10146,1014602,30146,"Albany, GA",GA,13,Georgia,34,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,0.0,-1.0,1200-1259,18.0,1211.0,1251.0,11.0,1304,-2.0,0.0,-1.0,1300-1359,1,0.0,19.216667
3,2018-01-26,Endeavor Air Inc.,ABY,ATL,False,False,1202,1150.0,0.0,-12.0,1253.0,0.0,35.0,62.0,63.0,145.0,2018,1,1,26,5,DL,DL_CODESHARE,19790,DL,3298,9E,20363,9E,N800AY,3298,10146,1014602,30146,"Albany, GA",GA,13,Georgia,34,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,0.0,-1.0,1200-1259,17.0,1207.0,1242.0,11.0,1304,-11.0,0.0,-1.0,1300-1359,1,0.0,19.166667
4,2018-01-27,Endeavor Air Inc.,ABY,ATL,False,False,1400,1355.0,0.0,-5.0,1459.0,0.0,36.0,60.0,64.0,145.0,2018,1,1,27,6,DL,DL_CODESHARE,19790,DL,3298,9E,20363,9E,N8839E,3298,10146,1014602,30146,"Albany, GA",GA,13,Georgia,34,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,0.0,-1.0,1400-1459,17.0,1412.0,1448.0,11.0,1500,-1.0,0.0,-1.0,1500-1559,1,0.0,22.583333